-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt

return {
	Luasnip.snippet(
		'cookbook_file',
		Format(
			[[
cookbook_file {} do
	source {}
	owner {}
	group {}
	mode {}
	action {}
end]],
			{
				Luasnip.insert_node(1),
				Luasnip.insert_node(2),
				Luasnip.insert_node(3),
				Luasnip.insert_node(4),
				Luasnip.insert_node(5),
				Luasnip.choice_node(
					6,
					{
						Luasnip.text_node(':create'),
						Luasnip.text_node(':create_if_missing'),
						Luasnip.text_node(':delete'),
						Luasnip.text_node(':nothing'),
					}
				),
			}
		)
	),
	Luasnip.snippet(
		'file',
		Format(
			[[
file {} do
	source {}
	owner {}
	group {}
	mode {}
	action {}
end]],
			{
				Luasnip.insert_node(1),
				Luasnip.insert_node(2),
				Luasnip.insert_node(3),
				Luasnip.insert_node(4),
				Luasnip.insert_node(5),
				Luasnip.choice_node(
					6,
					{
						Luasnip.text_node(':create'),
						Luasnip.text_node(':touch'),
						Luasnip.text_node(':delete'),
						Luasnip.text_node(':nothing'),
					}
				),
			}
		)
	),
	Luasnip.snippet(
		'directory',
		Format(
			[[
directory {} do
	source {}
	owner {}
	group {}
	mode {}
	action {}
end]],
			{
				Luasnip.insert_node(1),
				Luasnip.insert_node(2),
				Luasnip.insert_node(3),
				Luasnip.insert_node(4),
				Luasnip.insert_node(5),
				Luasnip.choice_node(
					6,
					{
						Luasnip.text_node(':create'),
						Luasnip.text_node(':delete'),
						Luasnip.text_node(':nothing'),
					}
				),
			}
		)
	),
	Luasnip.snippet(
		'package',
		Format(
			[[
package {} do
	action {}
end]],
			{
				Luasnip.insert_node(1),
				Luasnip.choice_node(
					2,
					{
						Luasnip.text_node(':install'),
						Luasnip.text_node(':upgrade'),
						Luasnip.text_node(':remove'),
						Luasnip.text_node(':purge'),
						Luasnip.text_node(':nothing'),
					}
				),
			}
		)
	),
	Luasnip.snippet(
		'service',
		Format(
			[[
service {} do
	enabled {}
	running {}
	action {}
end]],
			{
				Luasnip.insert_node(1),
				Luasnip.choice_node(
					2,
					{
						Luasnip.text_node('true'),
						Luasnip.text_node('false'),
					}
				),
				Luasnip.choice_node(
					3,
					{
						Luasnip.text_node('true'),
						Luasnip.text_node('false'),
					}
				),
				Luasnip.choice_node(
					4,
					{
						Luasnip.text_node(':enable'),
						Luasnip.text_node(':disable'),
						Luasnip.text_node(':start'),
						Luasnip.text_node(':stop'),
						Luasnip.text_node(':restart'),
						Luasnip.text_node(':reload'),
						Luasnip.text_node(':nothing'),
					}
				),
			}
		)
	),
}
