-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt

return {
	Luasnip.snippet(
		'ec',
		Format(
			[[
root = true

[*]
indent_style = {}
indent_size = tab
tab_width = {}
end_of_line = lf
charset = utf-8
insert_final_newline = true
max_line_length = {}
trim_trailing_whitespace = true]],
			{
				Luasnip.choice_node(
					1,
					{
						Luasnip.text_node('tab'),
						Luasnip.text_node('choice'),
					}
				),
				Luasnip.insert_node(2, '2'),
				Luasnip.insert_node(3, '80'),
			}
		)
	),
	Luasnip.snippet(
		'indent',
		Format(
			[[
indent_style = {}
indent_size = tab
tab_width = {}]],
			{
				Luasnip.choice_node(
					1,
					{
						Luasnip.text_node('tab'),
						Luasnip.text_node('choice'),
					}
				),
				Luasnip.insert_node(2, '2'),
			}
		)
	),
}
