-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt

return {
	Luasnip.snippet(
		'iferr',
		Format([[
if err != nil {{
	return {}
}}]],
			{ Luasnip.choice_node(1, { Luasnip.text_node('err'), Luasnip.text_node('nil, err') }) }
		)
	),
	Luasnip.snippet(
		'for',
		Format([[
for {} := range {} {{
	{}
}}]],
			{
				Luasnip.choice_node(1, { Luasnip.text_node('key, val'), Luasnip.text_node('_, val') }),
				Luasnip.insert_node(2),
				Luasnip.insert_node(0) }
		)
	),
}
