-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt
local Repeat = require('luasnip.extras').rep

return {
	Luasnip.snippet(
		'req',
		Format(
			[[local {} = require('{}')]],
			{ Luasnip.insert_node(1, 'module'), Repeat(1) }
		)
	),
	Luasnip.snippet(
		'preq',
		Format(
			[[local has_{}, {} = pcall(require, '{}')]],
			{ Luasnip.insert_node(1, 'module'), Repeat(1), Repeat(1) }
		)
	),
	Luasnip.snippet(
		'mf',
		Format(
			[[M.{} = function({})
	{}
end]],
			{ Luasnip.insert_node(1, 'func'), Luasnip.insert_node(2, 'params'), Luasnip.insert_node(0) }
		)
	),

	-- Meta-snippets
	Luasnip.snippet(
		'snippet',
		Format(
			[=[
Luasnip.snippet(
	'{}',
	Format(
		[[
{}
]],
		{{ {} }}
	)
),]=],
			{
				Luasnip.insert_node(1, 'name'),
				Luasnip.insert_node(2),
				Luasnip.insert_node(3),
			}
		)
	),
}
