-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt

return {
	Luasnip.snippet(
		'ifmain',
		Format(
			[[def main() -> int:
    {}

if __name__ == "__main__":
    main()]],
			{ Luasnip.insert_node(1) }
		)
	),
}
