-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt

return {
	Luasnip.snippet(
		'safe',
		Format(
			[[{}]],
			{ Luasnip.choice_node(1, { Luasnip.text_node('set -eu'), Luasnip.text_node('set -euo pipefail') }) }
		)
	),
}
