" Do not edit this file directly! It is managed by chezmoi.

let current_compiler = "jsonnet"

if exists(":CompilerSet") != 2
	command -nargs=* CompilerSet setlocal <args>
endif

let s:cpo_save = &cpo
set cpo&vim

CompilerSet makeprg=jsonnet\ -o\ /dev/null\ %
CompilerSet errorformat=%.%#\ %t%*[^:]:\ %f:%l:%c-%k:\ %m

let &cpo = s:cpo_save
unlet s:cpo_save
