-- Do not edit this file directly! It is managed by chezmoi.

vim.filetype.add({
	-- Map an extension to a file type.
	-- e.g. json = 'jsonc'
	extension = {},
	-- Map a file name to a file type.
	filename = {},
	-- Map a regex pattern to a file type
	pattern = {
		['.*%.config/git/config.*'] = 'gitconfig',
		['.*dot_config/git/config.*'] = 'gitconfig',
	},
})
