-- Do not edit this file directly! It is managed by chezmoi.

return {
	{ import = 'lazyvim.plugins.extras.lang.dotnet' },
	{ import = 'lazyvim.plugins.extras.lang.php' },
	{ import = 'lazyvim.plugins.extras.lang.tex' },
	{ import = 'lazyvim.plugins.extras.lang.typescript' },
}
