" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.
setlocal foldexpr=utils#Fold_Includes(v:lnum)
setlocal foldmethod=syntax
setlocal foldlevel=2
