" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.
syntax match tab display "\t"
highlight link tab Error

if executable('hh')
	let g:hack#hh_client = 'hh'
endif

setlocal autoindent
setlocal expandtab
setlocal shiftwidth=2
setlocal softtabstop=2

" Make XHP work?
setlocal iskeyword+=:,- iskeyword-=<
