" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.
setlocal nocindent
setlocal expandtab

call markdown#MathAndLiquid()

if exists('*litecorrect#init')
	call litecorrect#init(g:litecorrect_user_dict)
endif
