# vim: set filetype=toml:
# {{ $fontBasedir := ".local/share/fonts" }}
# {{ if eq .chezmoi.os "darwin" }}
# {{ $fontBasedir = "Library/Fonts" }}
# {{ else if eq .chezmoi.os "windows" }}
# {{ $fontBasedir = "AppData/Local/Microsoft/Windows/Fonts" }}
# {{ end }}
# {{ $scadBasedir := "Documents/OpenSCAD" }}
# {{ if eq .chezmoi.os "linux" }}
# {{ $scadBasedir = ".local/share/OpenSCAD" }}
# {{ end }}
["{{ $fontBasedir }}/FiraCode"]
url = '{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "FiraCode.zip" }}'
type = "archive"
exclude = [
	"README.md",
	"readme.md",
	"LICENSE",
	"*Propo-*",
	"*-Retina*",
	".uuid",
]
exact = true
refreshPeriod = "672h"

["{{ $fontBasedir }}/Hack"]
url = '{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "Hack.zip" }}'
type = "archive"
exclude = ["readme.md", "LICENSE.md", "*Propo-*", "README.md", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $fontBasedir }}/JetBrainsMono"]
url = '{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "JetBrainsMono.zip" }}'
type = "archive"
exclude = [
	"readme.md",
	"LICENSE.md",
	"OFL.txt",
	"JetBrainsMonoNL*",
	"*Propo-*",
	"README.md",
	".uuid",
]
exact = true
refreshPeriod = "672h"

["{{ $fontBasedir }}/Symbols"]
url = '{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "NerdFontsSymbolsOnly.zip" }}'
type = "archive"
exclude = [
	"readme.md",
	"LICENSE",
	"README.md",
	".uuid",
	"10-nerd-font-symbols.conf",
]
exact = true
refreshPeriod = "672h"

["{{ $fontBasedir }}/Fontin"]
type = "archive"
url = "http://www.exljbris.com/dl/fontin2_pc.zip"
exclude = ["ReadMe.txt", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $fontBasedir }}/codicon.ttf"]
type = "file"
url = "https://github.com/microsoft/vscode-codicons/releases/download/0.0.36/codicon.ttf"
refreshPeriod = "672h"

# {{ if ne .environment "work" }}
["{{ $scadBasedir }}/libraries/ub.scad"]
type = "file"
url = "https://github.com/UBaer21/UB.scad/raw/refs/heads/main/libraries/ub.scad"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

["{{ $scadBasedir }}/libraries/ShortCuts.scad"]
type = "file"
url = "https://www.thingiverse.com/download:11412285"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

["{{ $scadBasedir }}/libraries/relativity.scad"]
type = "file"
url = "https://github.com/davidson16807/relativity.scad/raw/refs/heads/master/relativity.scad"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

["{{ $scadBasedir }}/libraries/knurl.scad"]
type = "file"
url = "https://www.thingiverse.com/download:93142"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

["{{ $scadBasedir }}/libraries/knobs.scad"]
type = "file"
url = "https://www.thingiverse.com/download:140673"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

["{{ $scadBasedir }}/libraries/BOSL2"]
type = "archive"
url = "https://github.com/BelfrySCAD/BOSL2/archive/refs/heads/master.zip"
exact = true
stripComponents = 1
include = ["BOSL2-master/*.scad"]
refreshPeriod = "168h"

["{{ $scadBasedir }}/libraries/escad"]
type = "archive"
url = "https://vcs.jgoguen.ca/jgoguen/escad/archive/main.zip"
exact = true
stripComponents = 1
include = ["escad/*.scad"]
refreshPeriod = "168h"

["{{ $scadBasedir }}/libraries/gridfinity"]
type = "archive"
url = "https://github.com/ostat/gridfinity_extended_openscad/archive/refs/heads/main.zip"
exact = true
stripComponents = 1
refreshPeriod = "168h"
# {{ end }}

[".config/nvim/lua/neorg/modules/external/context/module.lua"]
type = "file"
url = "https://github.com/max397574/neorg-contexts/raw/master/lua/neorg/modules/external/context/module.lua"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "168h"

[".config/lazygit/catppuccin-mocha-mauve.yaml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/lazygit/main/themes-mergable/mocha/mauve.yml"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/joplin-desktop/userchrome.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userchrome.css"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/joplin-desktop/userstyle.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userstyle.css"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/kitty/current-theme.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

# {{- if ne .chezmoi.os "windows" }}
[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
exact = true
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-macchiato.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme"
filter.command = "tr"
filter.args = ["-d", "\r"]
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-latte.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-frappe.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_day.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_day.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_moon.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_moon.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_night.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_night.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_storm.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_storm.tmTheme"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_latte-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_latte-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_frappe-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_frappe-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_macchiato-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_macchiato-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"
# {{- end }}
