# {{- range $f := .fonts.nerdfonts }}
["{{ (index $.fonts.basedirs $.chezmoi.os) }}/{{ $f }}"]
url = '{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" (printf "%s.zip" $f) }}'
type = "archive"
exclude = [
	"LICENSE",
	"LICENSE.md",
	"LICENSE.txt",
	"README",
	"README.md",
	"readme.md",
	"OFL.txt",
	"JetBrainsMonoNL*",
	"*Propo-*",
	"*-Retina*",
	".uuid",
	"10-nerd-font-symbols.conf",
]
exact = true
refreshPeriod = "672h"
# {{- end }}

# {{- range .fonts.download }}
["{{ (index $.fonts.basedirs $.chezmoi.os) }}/{{ .name }}"]
type = "{{ .type }}"
url = "{{ .url }}"
exclude = ["ReadMe.txt", ".uuid"]
exact = true
refreshPeriod = "672h"
# {{- end }}

# {{- if ne .environment "work" }}
# {{- $scadBasedir := (index .scad.basedirs .chezmoi.os) }}
# {{- range .scad.libraries }}
["{{ $scadBasedir }}/libraries/{{ .name }}"]
type = "{{ .type }}"
url = "{{ .url }}"
# {{- if and (eq .type "file") (ne $.chezmoi.os "windows") }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
# {{- if and (eq .type "archive") (ne .strip nil) }}
stripComponents = {{ .strip }}
# {{- end }}
# {{- if ne .include nil }}
include = {{ .include | toToml }}
# {{- end }}
exact = true
refreshPeriod = "672h"
# {{- end }}
# {{- end }}

[".config/nvim/lua/neorg/modules/external/context/module.lua"]
type = "file"
url = "https://github.com/max397574/neorg-contexts/raw/master/lua/neorg/modules/external/context/module.lua"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "168h"

[".config/lazygit/catppuccin-mocha-mauve.yaml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/lazygit/main/themes-mergable/mocha/mauve.yml"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/joplin-desktop/userchrome.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userchrome.css"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/joplin-desktop/userstyle.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userstyle.css"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

[".config/kitty/current-theme.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf"
# {{- if ne .chezmoi.os "windows" }}
filter.command = "tr"
filter.args = ["-d", "\r"]
# {{- end }}
refreshPeriod = "672h"

# {{- if ne .chezmoi.os "windows" }}
[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
exact = true
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-macchiato.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme"
filter.command = "tr"
filter.args = ["-d", "\r"]
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-latte.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-frappe.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_day.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_day.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_moon.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_moon.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_night.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_night.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/tokyonight_storm.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/folke/tokyonight.nvim/refs/heads/main/extras/sublime/tokyonight_storm.tmTheme"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_latte-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_latte-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_frappe-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_frappe-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_macchiato-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_macchiato-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/plugins/fzf-tab"]
type = "git-repo"
exact = true
url = "https://github.com/Aloxaf/fzf-tab.git"
[".local/share/zsh/plugins/fzf-tab".clone]
args = ["--depth", "1"]

# {{- if eq .environment "work" }}
[".local/share/zsh/completion/_knife"]
type = "file"
url = "https://github.com/ohmyzsh/ohmyzsh/raw/refs/heads/master/plugins/knife/_knife"
refreshPeriod = "672h"
# {{- end }}

# {{- range (concat .zsh.plugins.common.omz (index .zsh.plugins .environment "omz")) }}
[".local/share/zsh/plugins/{{ . }}/{{ . }}.plugin.zsh"]
type = "file"
url = "https://github.com/ohmyzsh/ohmyzsh/raw/refs/heads/master/plugins/{{ . }}/{{ . }}.plugin.zsh"
refreshPeriod = "672h"

# {{- end }}
# {{- end }}
