
{{ $nerdFontVersion := "3.1.1" }}
{{ $basedir := ".local/share/fonts" }}
{{ if eq .chezmoi.os "darwin" }}
{{ $basedir = "Library/Fonts" }}
{{ end }}
# vim: set filetype=toml:
["{{ $basedir }}/FiraCode"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/FiraCode.zip"
exclude = ["readme.md", "LICENSE", "*Propo-*", "*-Retina*"]
refreshPeriod = "672h"

["{{ $basedir }}/Hack"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/Hack.zip"
exclude = ["readme.md", "LICENSE.md", "*Propo-*"]
refreshPeriod = "672h"

["{{ $basedir }}/JetBrainsMono"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/JetBrainsMono.zip"
exclude = ["readme.md", "LICENSE.md", "OFL.txt", "JetBrainsMonoNL*", "*Propo-*"]
refreshPeriod = "672h"

["{{ $basedir }}/Symbols"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ $nerdFontVersion }}/NerdFontsSymbolsOnly.zip"
exclude = ["readme.md", "LICENSE"]
refreshPeriod = "672h"

["{{ $basedir }}/Fontin"]
type = "archive"
url = "http://www.exljbris.com/dl/fontin2_pc.zip"
exclude = ["ReadMe.txt"]
refreshPeriod = "672h"

[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
exact = true
refreshPeriod = "672h"
