{{ $basedir := ".local/share/fonts" }}
{{ if eq .chezmoi.os "darwin" }}
{{ $basedir = "Library/Fonts" }}
{{ else if eq .chezmoi.os "windows" }}
{{ $basedir = "AppData/Local/Microsoft/Windows/Fonts" }}
{{ end }}
# vim: set filetype=toml:
["{{ $basedir }}/FiraCode"]
type = "archive"
url = "{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "FiraCode.zip" }}"
exclude = ["README.md", "readme.md", "LICENSE", "*Propo-*", "*-Retina*", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $basedir }}/Hack"]
type = "archive"
url = "{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "Hack.zip" }}"
exclude = ["readme.md", "LICENSE.md", "*Propo-*", "README.md", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $basedir }}/JetBrainsMono"]
type = "archive"
url = "{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "JetBrainsMono.zip" }}"
exclude = ["readme.md", "LICENSE.md", "OFL.txt", "JetBrainsMonoNL*", "*Propo-*", "README.md", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $basedir }}/Symbols"]
type = "archive"
url = "{{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "NerdFontsSymbolsOnly.zip" }}"
exclude = ["readme.md", "LICENSE", "README.md", ".uuid"]
exact = true
refreshPeriod = "672h"

["{{ $basedir }}/Fontin"]
type = "archive"
url = "http://www.exljbris.com/dl/fontin2_pc.zip"
exclude = ["ReadMe.txt", ".uuid"]
exact = true
refreshPeriod = "672h"

[".config/nvim/lua/neorg/modules/external/context/module.lua"]
type = "file"
url = "https://github.com/max397574/neorg-contexts/raw/master/lua/neorg/modules/external/context/module.lua"
refreshPeriod = "168h"

[".config/lazygit/catppuccin-mocha-mauve.yaml"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/lazygit/main/themes-mergable/mocha/mauve.yml"
refreshPeriod = "672h"

{{ if ne .chezmoi.os "windows" -}}
[".config/tmux/plugins/tpm"]
type = "archive"
url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
stripComponents = 1
exact = true
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-macchiato.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-latte.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
refreshPeriod = "672h"

[".config/bat/themes/Catppuccin-frappe.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_latte-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_latte-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_frappe-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_frappe-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"

[".local/share/zsh/catppuccin_macchiato-zsh-syntax-highlighting.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_macchiato-zsh-syntax-highlighting.zsh"
refreshPeriod = "672h"
{{- end }}

[".config/joplin-desktop/userchrome.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userchrome.css"
refreshPeriod = "672h"

[".config/joplin-desktop/userstyle.css"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/joplin/main/src/mocha/userstyle.css"
refreshPeriod = "672h"

[".config/kitty/current-theme.conf"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/kitty/main/themes/mocha.conf"
refreshPeriod = "672h"
