brew "bat"
brew "bottom"
brew "chezmoi"
brew "coreutils"
brew "fd"
brew "fortune"
brew "fzf"
brew "git"
brew "git-crypt"
brew "gnupg"
brew "go"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "lsd"
brew "lunchy"
brew "mas"
brew "neovim"
brew "npm"
brew "pinentry-mac"
brew "pre-commit"
brew "procs"
brew "pstree"
brew "python3"
brew "rename"
brew "ripgrep"
brew "sd"
brew "starship"
brew "thefuck"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "alfred"
cask "calibre"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "joplin"
cask "visual-studio-code"
cask "wezterm"

# App Store installs, find the ID and string to use with `mas list`
mas "1Password for Safari", id: 1569813296
mas "Baking Soda", id: 1601151613
mas "Hand Mirror", id: 1502839586
mas "OneDrive", id: 823766827
mas "Vinegar", id: 1591303229
