-- Do not edit this file directly! It is managed by chezmoi.

local Luasnip = require('luasnip')
local Format = require('luasnip.extras.fmt').fmt
local Partial = require('luasnip.extras').partial
local Utils = require('utils')

return {
	Luasnip.snippet(
		'dne',
		Format(
			"{comment} Do not edit this file directly! It is managed by chezmoi.\n\n",
			{ comment = Partial(Utils.comment_string) }
		)
	),
	Luasnip.snippet(
		'todo',
		Format(
			[[{comment} {} ({user}): ]],
			{
				Luasnip.choice_node(1, { Luasnip.text_node('TODO'), Luasnip.text_node('FIXME'), Luasnip.text_node('XXX') }),
				comment = Partial(Utils.comment_string),
				user = Partial(os.getenv, 'USER')
			}
		)
	),
	Luasnip.snippet('dmy', {
		Partial(os.date, '%d-%m-%Y'),
	}),
	Luasnip.snippet('ymd', {
		Partial(os.date, '%Y-%m-%d'),
	}),
	-- Apache 2.0 license
	Luasnip.snippet(
		'APACHE',
		Format(
			[[
{}
Copyright {year} {author}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

{}]],
			{
				Luasnip.insert_node(1, 'purpose'),
				year = Partial(os.date, '%Y'),
				author = Partial(os.getenv, 'USER'),
				Luasnip.insert_node(0)
			}
		)
	),
	-- MIT license
	Luasnip.snippet(
		'MIT',
		Format(
			[[
{}
Copyright (c) {year} {author}

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

{}]],
			{
				Luasnip.insert_node(1, 'purpose'),
				year = Partial(os.date, '%Y'),
				author = Partial(os.getenv, 'USER'),
				Luasnip.insert_node(0)
			}
		)
	),
}
