" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

" Enable vim-javascript highlighting for JSDocs
let g:javascript_plugin_jsdoc = 1

" Enable vim-javascript highlighting for Flow
let g:javascript_plugin_flow = 1
