-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'williamboman/mason-lspconfig.nvim',
	priority = 915,
	dependencies = {
		'williamboman/mason.nvim',
		'neovim/nvim-lspconfig',
	},
	opts = {
		automatic_installation = true,
	},
}

function M.config(plugin)
	local options = plugin.opts
	local has_config, config = pcall(require, 'config.mason-lspconfig')
	if has_config then
		options = vim.tbl_deep_extend('force', options, config)
	end
	require('mason-lspconfig').setup(options)

	--local lsputils = require('utils.lsp')
	--local registry = require('mason-registry')
	--local server_mappings = require('mason-lspconfig.mappings.server')

	--for _, server_name in ipairs(registry.get_installed_package_names()) do
	--	local lsp_name = server_mappings.package_to_lspconfig[server_name]
	--	lsputils.setup(lsp_name)
	--end
end

return M
