-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'windwp/nvim-ts-autotag',
	dependencies = {'nvim-treesitter/nvim-treesitter'},
	ft = {
		'hack', 'html', 'javascript', 'markdown', 'pandoc.markdown', 'php', 'xml',
	},
	config = true,
}

return M
