-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'weilbith/nvim-code-action-menu',
	cmd = 'CodeActionMenu',
}

function M.init()
	vim.g.code_action_menu_window_border = 'double'
end

return M
