-- Do not edit this file directly! It is managed by chezmoi.

local utils = require('utils')
local M = {
	'onsails/lspkind.nvim',
	dependencies = {
		'neovim/nvim-lspconfig',
	},
	opts = utils.lspkind_opts(),
}

function M.config(plugin)
	require('lspkind').init(plugin.opts)
end

return M
