-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'JoosepAlviste/nvim-ts-context-commentstring',
	dependencies = {'nvim-treesitter/nvim-treesitter'},
	event = 'VeryLazy',
}

return M
