-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'windwp/nvim-autopairs',
	dependencies = {
		'hrsh7th/nvim-cmp',
	},
	opts = {
		check_ts = true,
		ts_config = {
			java = false,
		},
		fast_wrap = {
			map = '<M-e>',
			chars = { '{', '[', '(', '"', "'" },
			pattern = string.gsub([[ [%'%"%)%>%]%)%}%,] ]], '%s+', ''),
			offset = 0,
			end_key = '$',
			keys = 'qwertyuiopzxcvbnmasdfghjkl',
			check_comma = true,
			highlight = 'PmenuSel',
			highlight_grey = 'LineNr',
		},
	},
}

function M.config(plugin)
	require('nvim-autopairs').setup(plugin.opts)

	local cmp = require('cmp')
	local autopair_cmp = require('nvim-autopairs.completion.cmp')
	local handlers = require('nvim-autopairs.completion.handlers')
	cmp.event:on(
		'confirm_done',
		autopair_cmp.on_confirm_done({
			filetypes = {
				['*'] = {
					['('] = {
						kind = {
							cmp.lsp.CompletionItemKind.Function,
							cmp.lsp.CompletionItemKind.Method,
						},
						handler = handlers["*"]
					},
				},
				latex = false,
				tex = false,
			},
		})
	)
end

return M
