-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'saadparwaiz1/cmp_luasnip',
	dependencies = {
		'hrsh7th/nvim-cmp',
	},
}

function M.config()
	local utils = require('utils')
	utils.add_cmp_source(utils.get_cmp_source('luasnip'))
end

return M
