-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'roobert/statusline-action-hints.nvim',
	dependencies = {
		'nvim-lualine/lualine.nvim'
	},
	lazy = true,
	opts = {
		definition_identifier = 'gd',
		template = '%s ref:%s',
	},
}

return M
