-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'nvim-telescope/telescope-fzf-native.nvim',
	dependencies = {'nvim-telescope/telescope.nvim'},
	event = 'VeryLazy',
	build = 'make',
}

function M.cond()
	return vim.fn.executable('make') ~= 0
end

function M.config()
	require('telescope').load_extension('fzf')
end

return M
