-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'folke/tokyonight.nvim',
	lazy = false,
	priority = 1000,
	opts = {
		style = 'night',
		styles = {
			comments = {
				italic = false,
			},
			keywords = {
				italic = false,
			},
		},
		sidebars = {
			'help',
			'lazy',
			'qf',
			'terminal',
		},
	},
}

function M.config(plugin)
	require('tokyonight').setup(plugin.opts)

	vim.cmd('colorscheme tokyonight')
end

return M
