-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'nathanaelkane/vim-indent-guides',
	event = 'VeryLazy',
}

function M.init()
	vim.g.indent_guides_enable_on_vim_startup = 1
end

return M
