-- Do not edit this file directly! It is managed by chezmoi.

local utils = require('utils')

local M = {
	's1n7ax/nvim-window-picker',
	version = 'v1.*',
	lazy = true,
	opts = {
		autoselect_one = true,
		include_current = true,
		filter_rules = {
			bo = {
				-- if the file type is one of following, the window will be ignored
				filetype = utils.excluded_filetypes,
				-- if the buffer type is one of following, the window will be ignored
				buftype = utils.excluded_buftypes,
			},
		},
	},
}

return M
