-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	active_colorscheme = 'tokyonight',
	themes = {
		tokyonight = {
			repo = 'folke/tokyonight.nvim',
			name = 'tokyonight.nvim',
			opts = {
				style = 'day',
				styles = {
					comments = {
						italic = false,
					},
					keywords = {
						italic = false,
					},
				},
				sidebars = {
					'help',
					'lazy',
					'qf',
					'terminal',
				},
			},
		},
		everblush = {
			repo = 'Everblush/nvim',
			name = 'everblush',
			opts = {},
		},
	},
}

return M
