-- Do not edit this file directly! It is managed by chezmoi.

local function first_line(bufnr)
	return vim.api.nvim_buf_get_lines(bufnr, 0, 1, false)[1] or ''
end

vim.filetype.add({
	extension = {
		cls = function(_, bufnr)
			if first_line(bufnr):match('^%%') then
				return 'latex'
			end
		end,
		gotmpl = 'gotmpl',
		jsonnet = 'jsonnet',
		libsonnet = 'jsonnet',
		markdown = 'markdown.pandoc',
		md = 'markdown.pandoc',
		mdown = 'markdown.pandoc',
		mkd = 'markdown.pandoc',
		mkdn = 'markdown.pandoc',
		mdwn = 'markdown.pandoc',
		opf = 'xml',
		scss = 'scss.css',
		tex = 'latex',
	},
	filename = {
		['.zprofile'] = 'zsh',
		['.zshenv'] = 'zsh',
		['.zlogin'] = 'zsh',
		['.zlogout'] = 'zsh',
		['.zshrc'] = 'zsh',
		PKGBUILD = 'sh',
		README = 'text',
	},
	pattern = {
		['(.+/)?chezmoi/.+%.tmpl$'] = 'gotmpl',
		['(.+/)?cookbooks/.*%.erb$'] = 'ruby.erb.chef',
		['(.+/)?cookbooks/.*%.rb$'] = 'ruby.eruby.chef',
		['(.+/)?roles/.*%.yml$'] = 'yaml.ansible',
		['.+'] = function(_, bufnr)
			local line = first_line(bufnr)
			if line:match('%f[%a]zsh%f[%A]') then
				return 'zsh'
			end
			if line:match('%f[%a]bash%f[%A]') or line:match('%f[%a]sh%f[%A]') then
				return 'sh'
			end
		end,
		['.*%.commit%.hg%.txt$'] = 'hgcommit',
		[vim.pesc((vim.env.XDG_DATA_HOME or (vim.env.HOME .. '/.local/share')) .. '/zsh/') .. '.*'] = 'zsh',
	},
})
