" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

if executable('gio')
	let g:graphviz_viewer = printf('%s open', exepath('gio'))
elseif executable('xdg-open')
	let g:graphviz_viewer = exepath('xdg-open')
elseif executable('open')
	let g:graphviz_viewer = exepath('open')
endif

let g:graphviz_output_format = 'svg'
