" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

let g:mkdp_auto_close = 0

let g:mkdp_refresh_slow = 1

" Markdown preview
nnoremap <Leader>mp <Plug>MarkdownPreviewToggle
