-- vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
-- vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
-- Do not edit this file directly! It is managed by chezmoi.

local present, go = pcall(require, 'go')
if not present then
	return
end

-- Only use gofmt for formatting
go.setup({
	auto_lint = false,
	formatter = 'gofmt',
})
