-- vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
-- vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
-- Do not edit this file directly! It is managed by chezmoi.

local present, treesitter = pcall(require, 'nvim-treesitter.configs')
if not present then
	return
end

treesitter.setup({
	autotag = {
		enable = true,
	},
	ensure_installed = {
		"bash", "c", "c_sharp", "comment", "cpp", "css", "dockerfile", "dot",
		"go", "gomod", "html", "http", "javascript", "jsdoc", "json", "json5",
		"jsonc", "latex", "lua", "make", "markdown", "php", "python", "ruby",
		"scss", "toml", "vim", "yaml",
	},
	highlight = { enable = true },
	incremental_selection = { enable = true },
	rainbow = {
		enable = true,
		extended_mode = true,
		max_file_lines = nil,
	},
	textobjects = { enable = true },
})
