-- vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
-- vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
-- Do not edit this file directly! It is managed by chezmoi.

local present, trouble = pcall(require, 'trouble')
if not present then
	return
end

trouble.setup({
	fold_closed = "▸",
	fold_open = "▾",
	open_split = { "<C-x>", "s" },
	open_vsplit = { "<C-v>", "i", "v" },
	open_tab = { "<C-t>", "t" },
	auto_open = true,
	auto_close = true,
	auto_preview = false,
	use_diagnostic_signs = true,
})
