-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'aznhe21/actions-preview.nvim',
	-- Prepare for aznhe21/actions-preview.nvim#62
	cond = function()
		local HasSnacks, _ = pcall(require, 'actions-preview.backend.snacks')
		return HasSnacks
	end,
	opts = {
		backend = { 'snacks' },
		diff = {
			ignore_whitespace = true,
		},
	},
}

return M
