-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'okuuva/auto-save.nvim',
	event = { 'BufLeave', 'FocusLost', 'InsertLeave', 'TextChanged' },
	opts = {
		noautocmd = true,
		condition = function(buf)
			local disable_for = {
				'norg',
			}
			local filetype = vim.fn.getbufvar(buf, '&filetype')

			return not vim.list_contains(disable_for, filetype)
		end,
	},
}

return M
