-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'okuuva/auto-save.nvim',
	event = { 'BufLeave', 'FocusLost', 'InsertLeave', 'TextChanged' },
	cond = function()
		local disable_for = {
			'norg',
		}
		return not vim.list_contains(disable_for, vim.bo.filetype)
	end,
	opts = {
		noautocmd = true,
	},
}

return M
