-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'okuuva/auto-save.nvim',
	event = { 'BufLeave', 'FocusLost', 'InsertLeave', 'TextChanged' },
	opts = {
		noautocmd = true,
		condition = function(buf)
			local disable_for = {
				'norg',
			}

			return not vim.tbl_contains(disable_for, vim.bo[buf].filetype)
		end,
	},
}

return M
