-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'akinsho/bufferline.nvim',
	opts = function(_, opts)
		local new_opts = {
			options = {
				always_show_bufferline = true,
				show_buffer_close_icons = false,
				show_close_icon = false,
			},
		}
		local HasCatppuccin, Catppuccin = pcall(require, 'catppuccin.groups.integrations.bufferline')

		if HasCatppuccin then
			new_opts.highlights = Catppuccin.get()
		end

		return vim.tbl_deep_extend('force', opts, new_opts)
	end,
}

return M
