-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'akinsho/bufferline.nvim',
	-- TODO: Remove init once LazyVim updates to include this fix, likely October or later
	init = function()
		local HasCatppuccin, CatppuccinBufline = pcall(require, 'catppuccin.groups.integrations.bufferline')
		if HasCatppuccin then
			function CatppuccinBufline.get()
				return CatppuccinBufline.get_theme()
			end
		end
	end,
	opts = function(_, opts)
		local new_opts = {
			options = {
				always_show_bufferline = true,
				show_buffer_close_icons = false,
				show_close_icon = false,
			},
		}
		local HasCatppuccin, Catppuccin = pcall(require, 'catppuccin.groups.integrations.bufferline')

		if HasCatppuccin then
			new_opts.highlights = Catppuccin.get()
		end

		return vim.tbl_deep_extend('force', opts, new_opts)
	end,
}

return M
