-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/tokyonight.nvim',
		opts = {
			style = vim.opt.background:get() == 'dark' and 'moon' or 'day',
			styles = {
				comments = {
					italic = false,
				},
				keywords = {
					italic = false,
				},
			},
			sidebars = {
				'help',
				'lazy',
				'qf',
				'terminal',
			},
		},
	},
	{
		'catppuccin/nvim',
		name = 'catppuccin',
		opts = {
			flavour = 'mocha',
			auto_integrations = false,
			integrations = {
				blink_cmp = true,
				dap = true,
				dap_ui = true,
				gitsigns = true,
				lsp_trouble = true,
				mason = true,
				mini = true,
				native_lsp = true,
				neotest = true,
				noice = true,
				notify = true,
				snacks = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
			transparent_background = true,
			background = {
				light = 'latte',
				dark = 'mocha',
			},
		},
	},
	{
		'LazyVim/LazyVim',
		opts = {
			colorscheme = vim.opt.background:get() == 'dark' and 'catppuccin-mocha' or 'catppuccin-latte',
		},
	},
}

return M
