-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		"stevearc/conform.nvim",
		init = function()
			vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
		end,
	},
}

return M
