-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'https://codeberg.org/esensar/nvim-dev-container',
	opts = {
		autocommands = {
			clean = true,
			update = true,
		},
		attach_mounts = {
			neovim_config = {
				enabled = true,
			},
			neovim_data = {
				enabled = true,
			},
		},
	},
}

return M
