-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	url = 'https://codeberg.org/jgoguen/git-linker.nvim',
	cond = function()
		-- Don't use LazyVim.root.cwd() here, it won't work at bootstrap
		local cwd = vim.uv.cwd()
		if cwd == '' then
			return false
		end

		return vim.fs.find('.git', { path = cwd, upward = true })[1] ~= nil
	end,
}

return M
