-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'akinsho/git-conflict.nvim',
	cond = function()
		-- Don't use LazyVim.root.cwd() here, it isn't available at bootstrap
		local cwd = vim.uv.cwd()
		if cwd == '' then
			return false
		end

		return vim.fs.find('.git', { path = cwd, upward = true })[1] ~= nil
	end,
	version = '*',
	opts = {
		default_mappings = {
			ours = '<LocalLeader>co',
			theirs = '<LocalLeader>ct',
			none = '<LocalLeader>c0',
			both = '<LocalLeader>cb',
			next = ']x',
			prev = '[x',
		},
	},
}

return M
