-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'akinsho/git-conflict.nvim',
	version = '*',
	opts = {
		default_mappings = {
			ours = '<LocalLeader>co',
			theirs = '<LocalLeader>ct',
			none = '<LocalLeader>c0',
			both = '<LocalLeader>cb',
			next = ']x',
			prev = '[x',
		},
	},
}

return M
