-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'dot-language-server' } },
	},
	{
		'neovim/nvim-lspconfig',
		opts = {
			servers = {
				dotls = {},
			},
		},
	},
	{
		'izocha/graphviz.nvim',
		enabled = function()
			return require('utils').has_tool('dot')
		end,
		ft = { 'dot' },
		opts = {},
	},
}

return M
