-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/lazydev.nvim',
		opts = function(_, opts)
			-- If cwd is in my code directory, remove the libraries specific to neovim configuration development
			local code_dir = os.getenv('HOME') .. '/Code/'
			if not vim.fn.getcwd():sub(1, #code_dir) == code_dir then
				return
			end

			local new_libs = {}
			for _, spec in ipairs(opts.library) do
				if type(spec) == 'table' and spec.path then
					if spec.path ~= 'LazyVim' and spec.path ~= 'snacks.nvim' and spec.path ~= 'lazy.nvim' then
						table.insert(new_libs, spec)
					end
				else
					table.insert(new_libs, spec)
				end
			end

			opts.library = new_libs
		end,
	},
}

return M
