-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'tristone13th/lspmark.nvim',
	dependencies = {
		'nvim-telescope/telescope.nvim',
	},
	config = function(_, _)
		require('lspmark').setup()
		require('telescope').load_extension('lspmark')
	end,
}

return M
