-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'rsreimer/codeowners.nvim',
		cond = function()
			return vim.fs.find('.github/CODEOWNERS', { path = LazyVim.root.cwd(), upward = true })[1] ~= nil
		end,
	},
	{
		'nvim-lualine/lualine.nvim',
		opts = function(_, opts)
			opts.theme = 'catppuccin'

			opts.options.disabled_filetypes = require('utils').excluded_filetypes

			table.insert(opts.sections.lualine_c, {
				function()
					return require('noice').api.status.lsp_progress.get_hl()
				end,
				cond = function()
					local has_noice, noice = pcall(require, 'noice')
					if not has_noice then
						return false
					end

					return noice.api.status.lsp_progress.has()
				end,
			})
			opts.sections.lualine_c[3] = { 'filetype' }
			opts.sections.lualine_c[4] = { LazyVim.lualine.pretty_path({ length = 0 }) }

			table.insert(opts.sections.lualine_x, 1, {
				function()
					return 'OWNERS: ' .. require('codeowners').get_buf_owner()
				end,
				cond = function()
					local HasCodeowners, Codeowners = pcall(require, 'codeowners')
					return HasCodeowners and Codeowners.get_buf_owner() ~= ''
				end,
			})

			opts.sections.lualine_y = {
				{ 'progress', separator = ' ', padding = { left = 1, right = 0 } },
				{ '%l/%L' },
				{ '%v' },
				{ '%B' },
			}

			table.insert(opts.sections.lualine_z, 1, function()
				local f = io.popen('/bin/hostname -s')
				if f == nil then
					return ''
				end
				local hostname = f:read('*a') or ''
				f:close()
				hostname = string.gsub(hostname, '\n$', '')
				return hostname
			end)
		end,
	},
}

return M
