-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'rsreimer/codeowners.nvim',
		cond = function()
			-- Do not use LazyVim.root.cwd() here, it isn't available at bootstrap
			return vim.fs.find('.github/CODEOWNERS', { path = vim.uv.cwd(), upward = true })[1] ~= nil
		end,
	},
	{
		'nvim-lualine/lualine.nvim',
		opts = function(_, opts)
			opts.theme = 'catppuccin'

			opts.options.disabled_filetypes = require('utils').excluded_filetypes

			table.insert(opts.sections.lualine_c, {
				function()
					return require('noice').api.status.lsp_progress.get_hl()
				end,
				cond = function()
					local has_noice, noice = pcall(require, 'noice')
					if not has_noice then
						return false
					end

					return noice.api.status.lsp_progress.has()
				end,
			})
			opts.sections.lualine_c[3] = { 'filetype' }
			opts.sections.lualine_c[4] = { LazyVim.lualine.pretty_path({ length = 0 }) }

			table.insert(opts.sections.lualine_x, 1, {
				function()
					local linters = require('lint').get_running()
					if #linters == 0 then
						return '󰦕'
					end
					return '󱉶 ' .. table.concat(linters, ', ')
				end,
				separator = require('lualine').get_config().options.component_separators,
				cond = function()
					local HasLint, _ = pcall(require, 'lint')
					return HasLint
				end,
			})

			table.insert(opts.sections.lualine_x, 2, {
				function()
					return 'OWNERS: ' .. require('codeowners').get_buf_owner()
				end,
				separator = require('lualine').get_config().options.component_separators,
				cond = function()
					local HasCodeowners, Codeowners = pcall(require, 'codeowners')
					return HasCodeowners and Codeowners.get_buf_owner() ~= ''
				end,
			})

			opts.sections.lualine_y = {
				{ 'progress', separator = ' ', padding = { left = 1, right = 0 } },
				{ '%l/%L' },
				{ '%v' },
				{ '%B' },
			}

			-- If running under tmux, a clock is provided by my tmux config already. The Lazyvim config for lualine inserts
			-- a clock as the first element in `lualine_z`.
			if vim.env.TMUX ~= nil then
				local z_sections = opts.sections.lualine_z or {}
				if #z_sections > 0 then
					table.remove(z_sections, 1)
				end
			end

			table.insert(opts.sections.lualine_z, 1, function()
				local f = io.popen('/bin/hostname -s')
				if f == nil then
					return ''
				end
				local hostname = f:read('*a') or ''
				f:close()
				hostname = string.gsub(hostname, '\n$', '')
				return hostname
			end)

			table.insert(opts.extensions, 'trouble')
		end,
	},
}

return M
