-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'vim-pandoc/vim-pandoc',
	lazy = false,
	init = function()
		vim.g['pandoc#filetypes#pandoc_markdown'] = 0
	end,
}

return M
