-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/snacks.nvim',
		keys = {
			{ '<leader>fe', false },
			{ '<leader>fE', false },
			{ '<leader>e', false },
			{ '<leader>E', false },
		},
	},
	{
		'nvim-mini/mini.files',
		version = false,
		opts = {
			mappings = {
				go_in = '<Right>',
				go_out = '<Left>',
			},
			windows = {
				preview = true,
				width_focus = 30,
				width_preview = 30,
			},
			options = {
				use_as_default_explorer = false,
			},
		},
		keys = {
			{
				'<leader>fe',
				function()
					local MiniFiles = require('mini.files')
					local current_win = vim.api.nvim_get_current_win()
					local root = vim.fs.normalize(LazyVim.root())
					local file = vim.fs.normalize(vim.api.nvim_buf_get_name(0))

					MiniFiles.open(root, false)
					MiniFiles.set_target_window(current_win)

					if file ~= '' and vim.startswith(file, root .. '/') then
						local branch = { root }
						local path = root
						for part in file:sub(#root + 2):gmatch('[^/]+') do
							path = path .. '/' .. part
							table.insert(branch, path)
						end
						MiniFiles.set_branch(branch)
					end
				end,
				desc = 'File Explorer (root dir)',
			},
			{
				'<leader>fE',
				function()
					local MiniFiles = require('mini.files')
					MiniFiles.open(vim.uv.cwd(), false)
					MiniFiles.set_target_window(vim.api.nvim_get_current_win())
				end,
				desc = 'File Explorer (cwd)',
			},
		},
		config = function(_, opts)
			local MiniFiles = require('mini.files')
			MiniFiles.setup(opts)

			local show_dotfiles = true
			local filter_show = function()
				return true
			end
			local filter_hide = function(fs_entry)
				return not vim.startswith(fs_entry.name, '.')
			end

			local toggle_dotfiles = function()
				show_dotfiles = not show_dotfiles
				MiniFiles.refresh({ content = { filter = show_dotfiles and filter_show or filter_hide } })
			end

			--- Pick a non-floating, non-special window. Returns the window ID directly
			--- if only one is eligible, or prompts with Snacks picker if multiple.
			---@return integer?
			local function pick_target()
				local Utils = require('utils')
				local eligible = {}
				for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
					if vim.api.nvim_win_get_config(win).relative == '' then
						local buf = vim.api.nvim_win_get_buf(win)
						if
							not vim.tbl_contains(Utils.excluded_buftypes, vim.bo[buf].buftype)
							and not vim.tbl_contains(Utils.excluded_filetypes, vim.bo[buf].filetype)
						then
							table.insert(eligible, win)
						end
					end
				end

				if #eligible == 0 then
					return nil
				end
				if #eligible == 1 then
					return eligible[1]
				end

				return Snacks.picker.util.pick_win({
					filter = function(win, buf)
						if vim.api.nvim_win_get_config(win).relative ~= '' then
							return false
						end
						return not vim.tbl_contains(Utils.excluded_buftypes, vim.bo[buf].buftype)
							and not vim.tbl_contains(Utils.excluded_filetypes, vim.bo[buf].filetype)
					end,
				})
			end

			--- Open the file under cursor. Optionally creates a split in the chosen
			--- base window first.
			---@param direction? string Split direction (e.g. 'belowright horizontal'), nil for no split
			local function open_in(direction)
				local entry = MiniFiles.get_fs_entry()
				if not entry or entry.fs_type ~= 'file' then
					return
				end

				local state = MiniFiles.get_explorer_state()
				if not state then
					return
				end

				local target = state.target_window

				local picked = pick_target()
				if not picked then
					return
				end
				target = picked

				if direction then
					local new_win = vim.api.nvim_win_call(target, function()
						vim.cmd(direction .. ' split')
						return vim.api.nvim_get_current_win()
					end)
					MiniFiles.set_target_window(new_win)
				else
					MiniFiles.set_target_window(target)
				end

				MiniFiles.go_in({ close_on_file = true })
			end

			vim.api.nvim_create_autocmd('User', {
				pattern = 'MiniFilesBufferCreate',
				callback = function(args)
					local buf_id = args.data.buf_id
					local map = function(lhs, rhs, desc)
						vim.keymap.set('n', lhs, rhs, { buffer = buf_id, desc = desc })
					end

					map('g.', toggle_dotfiles, 'Toggle hidden files')

					-- Pick a window first, then open or split from it
					map('<CR>', function()
						open_in(nil)
					end, 'Pick window and open')
					map('s', function()
						open_in('vertical')
					end, 'Pick window, open in horizontal split')
					map('v', function()
						open_in('horizontal')
					end, 'Pick window, open in vertical split')
					map('i', function()
						open_in('horizontal')
					end, 'Pick window, open in vertical split')
				end,
			})

			vim.api.nvim_create_autocmd('User', {
				pattern = 'MiniFilesActionRename',
				callback = function(event)
					Snacks.rename.on_rename_file(event.data.from, event.data.to)
				end,
			})
		end,
	},
}

return M
