-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/snacks.nvim',
		keys = {
			{ '<leader>fe', false },
			{ '<leader>fE', false },
			{ '<leader>e', false },
			{ '<leader>E', false },
		},
	},
	{
		'nvim-mini/mini.files',
		version = false,
		opts = {
			mappings = {
				go_in = '<Right>',
				go_out = '<Left>',
			},
			windows = {
				preview = true,
				width_focus = 30,
				width_preview = 30,
			},
			options = {
				use_as_default_explorer = false,
			},
		},
		keys = {
			{
				'<leader>fe',
				function()
					local MiniFiles = require('mini.files')
					local current_win = vim.api.nvim_get_current_win()
					local root = vim.fs.normalize(LazyVim.root())
					local file = vim.fs.normalize(vim.api.nvim_buf_get_name(0))

					MiniFiles.open(root, false)
					MiniFiles.set_target_window(current_win)

					if file ~= '' and vim.startswith(file, root .. '/') then
						local branch = { root }
						local path = root
						for part in file:sub(#root + 2):gmatch('[^/]+') do
							path = path .. '/' .. part
							table.insert(branch, path)
						end
						MiniFiles.set_branch(branch)
					end
				end,
				desc = 'File Explorer (root dir)',
			},
			{
				'<leader>fE',
				function()
					local MiniFiles = require('mini.files')
					MiniFiles.open(vim.uv.cwd(), false)
					MiniFiles.set_target_window(vim.api.nvim_get_current_win())
				end,
				desc = 'File Explorer (cwd)',
			},
		},
		config = function(_, opts)
			local MiniFiles = require('mini.files')
			MiniFiles.setup(opts)

			local show_dotfiles = true
			local filter_show = function()
				return true
			end
			local filter_hide = function(fs_entry)
				return not vim.startswith(fs_entry.name, '.')
			end

			local toggle_dotfiles = function()
				show_dotfiles = not show_dotfiles
				MiniFiles.refresh({ content = { filter = show_dotfiles and filter_show or filter_hide } })
			end

			vim.api.nvim_create_autocmd('User', {
				pattern = 'MiniFilesBufferCreate',
				callback = function(args)
					local buf_id = args.data.buf_id

					vim.keymap.set('n', '<CR>', function()
						MiniFiles.go_in({ close_on_file = true })
					end, { buffer = buf_id, desc = 'Open entry' })

					vim.keymap.set('n', 'g.', toggle_dotfiles, { buffer = buf_id, desc = 'Toggle hidden files' })
				end,
			})

			vim.api.nvim_create_autocmd('User', {
				pattern = 'MiniFilesActionRename',
				callback = function(event)
					Snacks.rename.on_rename_file(event.data.from, event.data.to)
				end,
			})
		end,
	},
}

return M
