-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'jakewvincent/mkdnflow.nvim',
		opts = {
			perspective = {
				priority = 'current',
				fallback = 'first',
			},
			links = {
				conceal = true,
			},
		},
	},
}

return M
