-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-neorg/neorg',
		lazy = false,
		ft = { 'norg' },
		version = '*',
		dependencies = {
			'nvim-lua/plenary.nvim',
			{
				'nvim-treesitter/nvim-treesitter',
				opts = {
					ensure_installed = { 'norg', 'norg_meta' },
				},
			},
		},
		opts = {
			load = {
				['core.defaults'] = {},

				['core.concealer'] = {},
				['core.dirman'] = {
					config = {
						workspaces = {
							notes = '~/OneDrive/Notes',
						},
						default_workspace = 'notes',
					},
				},
				['core.esupports.indent'] = {},
				['core.esupports.metagen'] = {
					config = {
						timezone = 'implicit-local',
						type = 'auto',
						update_date = true,
					},
				},
				['core.export'] = {
					config = {
						export_dir = os.getenv('HOME') .. '/Documents',
					},
				},
				['external.context'] = {},
			},
		},
	},
}

return M
