-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'vhyrro/luarocks.nvim',
		priority = 1000,
		config = true,
	},
	{
		'nvim-neorg/neorg',
		-- build = ':Neorg sync-parsers',
		cmd = 'Neorg',
		ft = { 'norg' },
		dependencies = {
			'nvim-lua/plenary.nvim',
			'vhyrro/luarocks.nvim',
		},
		opts = {
			load = {
				['core.defaults'] = {},

				['core.concealer'] = {},
				['core.dirman'] = {
					config = {
						workspaces = {
							notes = '~/OneDrive/Notes',
						},
						default_workspace = 'notes',
					},
				},
				['core.esupports.indent'] = {},
				['core.esupports.metagen'] = {
					config = {
						timezone = 'implicit-local',
						type = 'auto',
						update_date = true,
					},
				},
				['core.export'] = {
					config = {
						export_dir = os.getenv('HOME') .. '/Documents',
					},
				},
				['external.context'] = {},
			},
		},
	},
}

return M
