-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-neotest/neotest',
		dependencies = {
			{ 'sluongng/neotest-bazel' },
		},
		opts = function(_, opts)
			opts['adapters']['neotest-bazel'] = {}
			opts['adapters']['neotest-python'] = opts['adapters']['neotest-python'] or {}
			opts['adapters']['neotest-python']['python'] = vim.g.python3_host_prog
		end,
	},
}

return M
