-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-neotest/neotest',
		opts = {
			adapters = {
				['neotest-python'] = {
					python = vim.g.python3_host_prog,
				},
			},
		},
	},
}

return M
