-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'folke/noice.nvim',
	opts = {
		messages = {
			view_history = 'popup',
		},
		commands = {
			history = {
				view = 'popup',
			},
		},
		presets = {
			lsp_doc_border = false,
		},
		lsp = {
			signature = {
				auto_open = {
					enabled = false,
				},
			},
		},
		status = {
			lsp_progress = {
				event = 'lsp',
				kind = 'progress',
			},
		},
		routes = {
			-- Don't show LSP progress in the default view
			{
				filter = {
					event = 'lsp',
					kind = 'progress',
				},
				opts = {
					skip = true,
				},
			},
			-- Don't show :make messages
			-- Assumes the default value for shellpipe
			{
				filter = {
					cmdline = 'make',
					find = ' tee ',
					error = false,
				},
				opts = {
					skip = true,
				},
			},
		},
	},
}

return M
