-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.diagnostics = opts.diagnostics or {}
			opts.servers = opts.servers or {}
			opts.servers['*'] = opts.servers['*'] or {}

			opts.diagnostics.virtual_text = false

			local capabilities = {
				offsetEncoding = { 'utf-16' },
				general = {
					positionEncodings = { 'utf-16' },
				},
			}
			opts.servers['*'].capabilities = vim.tbl_deep_extend('force', opts.servers['*'].capabilities or {}, capabilities)
		end,
	},
}

return M
