-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.diagnostics = opts.diagnostics or {}
			opts.servers = opts.servers or {}
			opts.servers['*'] = opts.servers['*'] or {}

			opts.diagnostics.virtual_text = false

			local capabilities = {
				offsetEncoding = { 'utf-16' },
				general = {
					positionEncodings = { 'utf-16' },
				},
			}
			opts.servers['*'].capabilities = vim.tbl_deep_extend('force', opts.servers['*'].capabilities or {}, capabilities)

			opts.servers.jsonls = opts.servers.jsonls or {}
			opts.servers.jsonls.settings = opts.servers.jsonls.settings or {}
			opts.servers.jsonls.settings.json = opts.servers.jsonls.settings.json or {}
			opts.servers.jsonls.settings.json.validate = { enable = true }
		end,
	},
}

return M
