-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'NvChad/nvim-colorizer.lua',
	event = 'VeryLazy',
	opts = {
		user_default_options = {
			names = false,
		},
	},
}

return M
