-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	-- Temporary pinning until lazy.nvim updates to remove its usage of
	-- mason-lspconfig.mappings.server for Mason v2.
	{ 'mason-org/mason.nvim', version = '1.11.0' },
	{ 'mason-org/mason-lspconfig.nvim', version = '1.32.0' },
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.diagnostics.virtual_text = false
			opts.capabilities['offsetEncoding'] = { 'utf-16' }
			opts.capabilities['general'] = opts.capabilities['general'] or {}
			opts.capabilities.general['positionEncodings'] = { 'utf-16' }
		end,
	},
}

return M
