-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'Nickvandyke/opencode.nvim',
	version = '*',
	dependencies = {
		---@module "snacks"
		{
			'folke/snacks.nvim',
		},
		---@module "which-key"
		{
			'folke/which-key.nvim',
			opts = {
				spec = {
					{ '<Leader>a', mode = { 'n', 'x' }, group = 'OpenCode' },
					{ '<Leader>ap', mode = { 'n', 'x' }, group = 'Prompt' },
				},
			},
		},
	},
	config = function()
		---@type opencode.Opts
		vim.g.opencode_opts = {}
		vim.o.autoread = true -- Required for `opts.events.reload`

		vim.api.nvim_create_autocmd({ 'TermOpen' }, {
			group = vim.api.nvim_create_augroup('opencode_buffer', { clear = false }),
			pattern = '*:opencode --port*',
			desc = 'Assign binds specific to OpenCode buffers',
			callback = function(event)
				local bufname = vim.api.nvim_buf_get_name(event.buf) ---@type string

				-- Example: ``term:/…/nvim/lua/plugins//58118:opencode --port`
				-- The dashes in `--port` must be escaped because it is a special
				-- character in Lua's flavour of regex patterns.
				if string.match(bufname, '^term:.+//%d+:opencode %-%-port.*$') then
					require('which-key').add({
						buffer = event.buf,
						mode = { 'n', 't' },
						{
							'<C-U>',
							function()
								require('opencode').command('session.half.page.up')
							end,
							desc = 'Half scroll backward',
						},
						{
							'<C-D>',
							function()
								require('opencode').command('session.half.page.down')
							end,
							desc = 'Half scroll forward',
						},
						{
							'<C-B>',
							function()
								require('opencode').command('session.page.up')
							end,
							desc = 'Scroll backward',
						},
						{
							'<C-F>',
							function()
								require('opencode').command('session.page.down')
							end,
							desc = 'Scroll forward',
						},
					})
				end
			end,
		})
	end,
	keys = {
		{
			'<leader>aa',
			function()
				require('opencode').toggle()
			end,
			mode = { 'n', 't' },
			desc = 'Toggle',
		},
		{
			'<leader>as',
			function()
				require('opencode').select()
			end,
			mode = { 'n', 'x' },
			desc = 'Select action',
		},
		------------------------------------------------------------------------------------------------------
		{
			'<leader>ai',
			function()
				require('opencode').ask('', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Ask',
		},
		{
			'<leader>aI',
			function()
				require('opencode').ask('@this: ', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Ask with context',
		},
		{
			'<leader>ab',
			function()
				require('opencode').ask('@file: ', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Ask about buffer',
		},
		------------------------------------------------------------------------------------------------------
		{
			'<leader>ape',
			function()
				require('opencode').prompt('explain', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Explain',
		},
		{
			'<leader>apf',
			function()
				require('opencode').prompt('fix', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Fix',
		},
		{
			'<leader>apd',
			function()
				require('opencode').prompt('diagnose', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Diagnose',
		},
		{
			'<leader>apr',
			function()
				require('opencode').prompt('review', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Review',
		},
		{
			'<leader>apt',
			function()
				require('opencode').prompt('test', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Test',
		},
		{
			'<leader>apo',
			function()
				require('opencode').prompt('optimize', { submit = true })
			end,
			mode = { 'n', 'x' },
			desc = 'Optimize',
		},
		------------------------------------------------------------------------------------------------------
		{
			'go',
			function()
				return require('opencode').operator('@this ')
			end,
			expr = true,
			mode = { 'n', 'x' },
			desc = 'Add range to OpenCode',
		},
		{
			'goo',
			function()
				return require('opencode').operator('@this ') .. '_'
			end,
			expr = true,
			mode = { 'n' },
			desc = 'Add line to OpenCode',
		},
	},
}

return M
