-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-orgmode/orgmode',
		event = 'VeryLazy',
		ft = { 'org' },
		opts = {
			org_agenda_files = { '~/Documents/org/**/*' },
			org_default_notes_file = '~/Documents/org/refile.org',
			win_split_mode = 'vertical',
			win_border = { '╔', '═', '╗', '║', '╝', '═', '╚', '║' },
			org_startup_folded = 'content',
			org_hide_emphasis_markers = true,
			org_log_into_drawer = 'LOGBOOK', -- nil to log into the section body, recommended to set to 'LOGBOOK'
			calendar_week_start_day = 0, -- 0-Sunday, 1-Monday, etc.

			-- Set up notifications via system notification manager and Snacks.nvim if this sticks
			-- See https://nvim-orgmode.github.io/configuration#notifications

			ui = {
				agenda = {
					preview_window = {
						wrap = true,
						border = { '╔', '═', '╗', '║', '╝', '═', '╚', '║' },
					},
				},
				input = {
					use_vim_ui = true,
				},
			},
		},
	},
}

return M
