-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'winston0410/range-highlight.nvim',
	event = { 'BufReadPost' },
	dependencies = {
		'winston0410/cmd-parser.nvim',
	},
	opts = {},
}

return M
