-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/snacks.nvim',
		priority = 1000,
		lazy = false,
		opts = function(_, opts)
			local new_opts = {
				bigfile = {
					enabled = true,
					size = 5 * 1024 * 1024, -- 5MiB
				},
				bufdelete = {
					enabled = true,
				},
				explorer = {
					enabled = false,
				},
				git = {
					enabled = true,
				},
				gitbrowse = {
					enabled = true,
					url_patterns = {
						['vcs.jgoguen.ca'] = {
							branch = '/src/branch/{branch}',
							file = '/src/branch/{branch}/{file}#L{line}',
						},
					},
				},
				indent = {
					chunk = {
						enabled = true,
					},
				},
				lazygit = {
					enabled = true,
				},
				notifier = {
					style = 'fancy',
				},
				picker = {
					matcher = {
						frecency = true,
					},
					sources = {
						files = {
							hidden = true,
						},
					},
					win = {
						preview = {
							wo = {
								wrap = true,
							},
						},
					},
				},
				rename = {
					enabled = true,
				},
				scroll = {
					duration = {
						step = 15,
						total = 150,
					},
					enabled = true,
				},
				terminal = {
					win = {
						position = 'float',
					},
				},
				win = {
					border = 'double',
				},
				words = {
					enable = true,
				},
			}

			table.insert(
				opts.dashboard.preset.keys,
				7,
				{ icon = 'S', key = 'S', desc = 'Select Session', action = require('persistence').select }
			)

			return vim.tbl_deep_extend('force', opts, new_opts)
		end,
	},
}

return M
