-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'folke/snacks.nvim',
		priority = 1000,
		lazy = false,
		opts = function(_, opts)
			local new_opts = {
				bigfile = {
					enabled = true,
					size = 5 * 1024 * 1024, -- 5MiB
				},
				bufdelete = {
					enabled = true,
				},
				explorer = {
					enabled = true,
				},
				git = {
					enabled = true,
				},
				gitbrowse = {
					enabled = true,
					url_patterns = {
						['vcs.jgoguen.ca'] = {
							branch = '/src/branch/{branch}',
							file = '/src/branch/{branch}/{file}#L{line}',
						},
					},
				},
				lazygit = {
					enabled = true,
				},
				picker = {
					matcher = {
						frecency = true,
					},
					sources = {
						explorer = {
							formatters = {
								file = {
									filename_only = false,
								},
							},
							git_status = true,
							git_status_open = true,
							git_untracked = true,
							win = {
								list = {
									keys = {
										['<CR>'] = { 'handle_file_or_dir', mode = { 'n', 'i' } },
										['s'] = { { 'pick_win', 'edit_vsplit' }, mode = { 'n', 'i' } },
										['i'] = { { 'pick_win', 'edit_split' }, mode = { 'n', 'i' } },
									},
								},
							},
							actions = {
								handle_file_or_dir = require('utils.snacks').explorer_confirm,
							},
						},
					},
				},
				rename = {
					enabled = true,
				},
				scroll = {
					duration = {
						step = 15,
						total = 150,
					},
					enabled = true,
				},
			}

			table.insert(
				opts.dashboard.preset.keys,
				7,
				{ icon = 'S', key = 'S', desc = 'Select Session', action = require('persistence').select }
			)

			return vim.tbl_deep_extend('force', opts, new_opts)
		end,
		keys = {
			{
				'<leader>fe',
				function()
					local explorer = Snacks.picker.get({ source = 'explorer' })[1]
					if explorer == nil then
						Snacks.explorer({ cwd = LazyVim.root() })
						return
					end

					local file = vim.fs.normalize(vim.api.nvim_buf_get_name(0))
					Snacks.explorer.reveal({ file = file })
					explorer:focus('list', { show = true })
				end,
				desc = 'File Explorer (root dir)',
			},
			{
				'<leader>fE',
				function()
					local explorer = Snacks.picker.get({ source = 'explorer' })[1]
					if explorer == nil then
						Snacks.explorer()
						return
					end

					local file = vim.fs.normalize(vim.api.nvim_buf_get_name(0))
					Snacks.explorer.reveal({ file = file })
					explorer:focus('list', { show = true })
				end,
				desc = 'File Explorer (cwd)',
			},
		},
	},
}

return M
