-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local select_window = function(type)
	return function(bufnr)
		local TelescopeActionSet = require('telescope.actions.set')
		local TelescopeActionState = require('telescope.actions.state')
		local picker = TelescopeActionState.get_current_picker(bufnr)

		picker.get_selection_window = function(window_picker)
			window_picker.get_selection_window = nil
			local wp_opts = Utils.window_picker_opts
			wp_opts.filter_rules['include_current_win'] = true
			return require('window-picker').pick_window(wp_opts) or vim.api.nvim_get_current_win()
		end

		return TelescopeActionSet.select(bufnr, type)
	end
end

local M = {
	{
		'nvim-telescope/telescope.nvim',
		dependencies = {
			{
				'otavioschwanck/telescope-alternate.nvim',
				opts = function(_, opts)
					opts = opts or {}

					opts['presets'] = { 'go' }
					opts['mappings'] = {}
					opts['telescope_mappings'] = require('telescope-alternate').default_mappings
					opts['telescope_mappings']['i']['open_horizontal'] = '<C-i>'
					opts['telescope_mappings']['i']['open_vertical'] = '<C-s>'
					opts['telescope_mappings']['n']['open_horizontal'] = '<C-i>'
					opts['telescope_mappings']['n']['open_vertical'] = '<C-s>'
				end,
				config = function(_, opts)
					require('telescope-alternate').setup(opts)

					LazyVim.on_load('telescope.nvim', function()
						local ok, err = pcall(require('telescope').load_extension, 'telescope-alternate')
						if not ok then
							LazyVim.error('Failed to load telescope-alternate:\n' .. err)
						end
					end)
				end,
			},
		},
		opts = {
			defaults = {
				path_display = {
					'truncate',
				},
				sorting_strategy = 'ascending',
				layout_config = {
					horizontal = {
						prompt_position = 'top',
						preview_width = 0.55,
						results_width = 0.8,
					},
					vertical = {
						mirror = false,
					},
					width = 0.87,
					height = 0.80,
					preview_cutoff = 120,
				},
				mappings = {
					i = {
						['<CR>'] = select_window('default'),
						['<C-s>'] = select_window('vertical'),
						['<C-i>'] = select_window('horizontal'),
					},
					n = {
						['<CR>'] = select_window('default'),
						s = select_window('vertical'),
						i = select_window('horizontal'),
					},
				},
			},
		},
	},
}

return M
