-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'rachartier/tiny-inline-diagnostic.nvim',
	opts = {
		options = {
			break_line = {
				enabled = true,
			},
			multilines = true,
			multiple_diag_under_cursor = true,
			show_source = true,
		},
	},
}

return M
