-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'rachartier/tiny-inline-diagnostic.nvim',
	event = { 'LspAttach' },
	priority = 1000,
	opts = {
		options = {
			break_line = {
				enabled = true,
			},
			multilines = true,
			show_source = true,
		},
	},
}

return M
