-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'rachartier/tiny-inline-diagnostic.nvim',
	opts = {
		options = {
			multiple_diag_under_cursor = true,
		},
	},
}

return M
