-- Do not edit this file directly! It is managed by chezmoi.

local extra_parsers = {
	'comment',
	'gotmpl',
	'ssh_config',
	'proto',
	'tmux',
}

local M = {
	'nvim-treesitter/nvim-treesitter',
	dependencies = {
		'RRethy/nvim-treesitter-endwise',
		'ngalaiko/tree-sitter-go-template',
		'windwp/nvim-ts-autotag',
	},
	opts = function(_, opts)
		opts.highlight.disable = function()
			if string.find(vim.bo.filetype, 'chezmoitmpl') then
				return true
			end
		end
		opts.highlight.additional_vim_regex_highlighting = { 'markdown', 'markdown.pandoc' }
		opts.autotag = { enable = true }
		opts.endwise = { enable = true }
		for _, p in ipairs(extra_parsers) do
			table.insert(opts.ensure_installed, p)
		end
	end,
}

return M
