-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'folke/trouble.nvim',
	opts = {
		mode = 'document_diagnostics',
		open_split = { '<C-x>', 's' },
		open_vsplit = { '<C-v>', 'i', 'v' },
		open_tab = { '<C-t>', 't' },
		auto_close = true,
		auto_preview = true,
	},
}

return M
