-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'folke/ts-comments.nvim',
	opts = function(_, opts)
		local new_opts = {
			lang = {
				openscad = '// %s',
				snippets = '# %s',
			},
		}

		return vim.tbl_deep_extend('force', opts, new_opts)
	end,
}

return M
