-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'folke/ts-comments.nvim',
	opts = function(_, opts)
		local new_opts = {
			openscad = '// %s',
			snippets = '# %s',
		}

		opts.lang = vim.tbl_deep_extend('force', opts.lang, new_opts)
	end,
}

return M
