-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'akinsho/git-conflict.nvim',
		cond = function()
			-- Don't use LazyVim.root.cwd() here, it isn't available at bootstrap
			local cwd = vim.uv.cwd()
			if cwd == '' then
				return false
			end

			return vim.fs.find('.git', { path = cwd, upward = true })[1] ~= nil
		end,
		version = '*',
		opts = {
			default_mappings = {
				ours = '<LocalLeader>co',
				theirs = '<LocalLeader>ct',
				none = '<LocalLeader>c0',
				both = '<LocalLeader>cb',
				next = ']x',
				prev = '[x',
			},
		},
	},
	{
		url = 'https://codeberg.org/jgoguen/git-linker.nvim',
		cond = function()
			-- Don't use LazyVim.root.cwd() here, it won't work at bootstrap
			local cwd = vim.uv.cwd()
			if cwd == '' then
				return false
			end

			return vim.fs.find('.git', { path = cwd, upward = true })[1] ~= nil
				or vim.fs.find('.jj', { path = cwd, upward = true })[1] ~= nil
		end,
	},
	{
		'nicolasgb/jj.nvim',
		version = '*', -- Use latest stable release
		opts = {
			editor = {
				window = {
					type = 'floating',
				},
			},
			terminal = {
				window = {
					type = 'floating',
				},
			},
			log = {
				close_on_edit = true,
			},
		},
		keys = function(_, keys)
			local function add_key(key, func, desc)
				table.insert(keys, {
					key,
					func,
					desc = desc,
				})
			end

			local HasPicker, Picker = pcall(require, 'jj.picker')
			if HasPicker then
				add_key('<Leader>gj', function()
					Picker.status()
				end, 'Open JJ status picker')
				add_key('<Leader>jgs', function()
					Picker.conflict_sections()
				end, 'Open JJ conflict sections picker')
			end
		end,
	},
}

return M
