-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local function pick_window()
	local has_picker, WindowPicker = pcall(require, 'window-picker')
	if has_picker then
		local wid = WindowPicker.pick_window() or vim.api.nvim_get_current_win()
		vim.api.nvim_set_current_win(wid)
	end
end

local M = {
	's1n7ax/nvim-window-picker',
	version = '2.*',
	keys = {
		{ '<Leader>wp', pick_window, desc = 'Pick window' },
	},
	opts = Utils.window_picker_opts,
}

return M
