-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		"williamboman/mason.nvim",
		opts = function(_, opts)
			table.insert(opts.ensure_installed, "golines")
		end,
	},
	{
		"stevearc/conform.nvim",
		opts = function(_, opts)
			opts.formatters_by_ft["go"] = opts.formatters_by_ft["go"] or {}
			table.insert(opts.formatters_by_ft.go, "golines")
		end,
	},
}

return M
