-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = {
			servers = {
				gopls = {
					settings = {
						gopls = {
							['local'] = 'go.jgoguen.ca/',
						},
					},
				},
			},
		},
	},
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'golines' } },
	},
	{
		'stevearc/conform.nvim',
		opts = function(_, opts)
			opts.formatters_by_ft['go'] = opts.formatters_by_ft['go'] or {}
			table.insert(opts.formatters_by_ft.go, 'golines')

			opts.formatters.goimports = opts.formatters.goimports or {}
			-- opts.formatters.goimports.prepend_args = {
			-- 	"-local",
			-- 	"go.jgoguen.ca/",
			-- }
		end,
	},
}

return M
