-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local M = {
	'olexsmir/gopher.nvim',
	build = ':GoInstallDeps',
	ft = 'go',
	enabled = Utils.has_tool('go'),
	opts = {},
}

return M
