-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	"neovim/nvim-lspconfig",
	opts = {
		servers = {
			ansiblels = {
				settings = {
					ansible = {
						python = {
							interpreterPath = "python3",
						},
						validation = {
							lint = {
								enabled = false,
							},
						},
					},
				},
			},
			clangd = {
				capabilities = {
					offsetEncoding = "utf-8",
				},
			},
			pyright = {
				settings = {
					python = {
						pythonPath = "python3",
					},
				},
			},
		},
	},
}

return M
