-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = {
			settings = {
				openscad_lsp = {
					-- An empty string is required here if there are no paths to provide because openscad-lsp doesn't check for
					-- this value being missing but empty is fine.
					search_paths = '',
					fmt_style = 'file',
				},
			},
		},
	},
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'openscad-lsp' } },
	},
}

return M
