-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'mrcjkb/rustaceanvim',
		opts = {
			server = {
				cmd = function()
					local cwd = vim.fn.getcwd()
					local stat = vim.uv.fs_stat(cwd .. '/.envrc')

					local stable_ra = vim.fn.systemlist({
						'rustup',
						'which',
						'--toolchain',
						'stable',
						'rust-analyzer',
					})[1]

					if stat ~= nil and stat.type == 'file' then
						return { 'direnv', 'exec', cwd, stable_ra }
					end
					return { stable_ra }
				end,
				default_settings = {
					['rust-analyzer'] = {
						cargo = {
							buildScripts = {
								enable = true,
							},
						},
						checkOnSave = true,
					},
				},
			},
		},
	},
}

return M
