-- Do not edit this file directly! It is managed by chezmoi.

return {
	settings = {
		json = {
			schemas = require('schemastore').json.schemas(),
			validate = {
				enable = true,
			},
		},
	},
}
