-- Do not edit this file directly! It is managed by chezmoi.

return {
	settings = {
		python = {
			analysis = {
				autoImportCompletions = true,
				autoSearchPaths = true,
				diagnosticMode = 'workspace',
				useLibraryCodeForTypes = true,
			},
		},
	}
}
