# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

if (( ${+commands[conda]} )); then
	__conda_setup="$(conda shell.zsh hook 2>/dev/null)"
	if [ -n "${__conda_setup}" ]; then
		eval "${__conda_setup}"
	else
		if [ -f /usr/etc/profile.d/conda.sh ]; then
			. /usr/etc/profile.d/conda.sh
		fi
	fi
	unset __conda_setup
fi
