# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

if (( ${+commands[gpg-agent]} )); then
	gpgconf --launch gpg-agent
	export GPG_AGENT_INFO="$(gpgconf --list-dirs agent-socket)"
fi

MY_TTY=$(/usr/bin/tty)
if [ -n "${MY_TTY}" ]; then
	export GPG_TTY="${MY_TTY}"
fi
