-- Do not edit this file directly! It is managed by chezmoi.

local colorscheme = require('config.colorscheme')

local M = {
	colorscheme.themes[colorscheme.active_colorscheme].repo,
	name = colorscheme.themes[colorscheme.active_colorscheme].name,
	lazy = false,
	priority = 1000,
	opts = colorscheme.themes[colorscheme.active_colorscheme].opts,
}

function M.config(plugin)
	local colorscheme = require('config.colorscheme')
	require(colorscheme.active_colorscheme).setup(plugin.opts)

	vim.cmd('colorscheme ' .. colorscheme.active_colorscheme)
end

return M
