-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'lukas-reineke/indent-blankline.nvim',
	dependencies = {
		'nathanaelkane/vim-indent-guides',
	},
	event = 'VeryLazy',
	opts = {
		buftype_exclude = {
			'nofile',
			'prompt',
			'quickfix',
			'terminal',
		},
		filetype_exclude = {
			'dashboard',
			'neogitstatus',
			'NvimTree',
			'neo-tree',
			'neo-tree-popup',
			'notify',
			'packer',
			'TelescopePrompt',
			'Trouble',
		},
		context_patterns = {
			'class',
			'return',
			'function',
			'method',
			'^if',
			'^while',
			'jsx_element',
			'^for',
			'^object',
			'^table',
			'block',
			'arguments',
			'if_statement',
			'else_clause',
			'jsx_element',
			'jsx_self_closing_element',
			'try_statement',
			'catch_clause',
			'import_statement',
			'operation_type',
		},
		show_trailing_blankline_indent = false,
		use_treesitter = true,
		char = '▏',
		context_char = '▏',
		show_current_context = true,
	},
}

return M
