-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'ErichDonGubler/lsp_lines.nvim',
	dependencies = {
		'neovim/nvim-lspconfig',
	},
	event = 'VeryLazy',
	opts = {},
}

return M
