-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'nvim-lualine/lualine.nvim',
	event = 'VeryLazy',
	opts = {
		options = {
			theme = 'auto',
			disabled_filetypes = require('utils').excluded_filetypes,
			globalstatus = true,
		},
		extensions = {
			'neo-tree',
			'quickfix',
			'trouble',
			'aerial',
			'lazy',
		},
		sections = {
			lualine_c = {
				{
					'filename',
					path = 1,
					newfile_status = true,
				},
			},
			lualine_x = {},
			lualine_y = {},
			lualine_z = {
				{'progress'},
				{'%l/%L'},
				{'%v'},
				{'%B'},
			},
		},
		tabline = {
			lualine_a = {
				{
					'buffers',
					show_filename_only = false,
				},
			},
			lualine_z = {
				{
					'tabs',
					-- 0: Tab number only
					-- 1: Tab name only
					-- 2: Show tab number and name
					mode = 2,
				},
			},
		},
	},
}

function M.config(plugin)
	local Colorscheme = require('config.colorscheme')
	local has_cs, cs = pcall(require, 'lualine.themes.' .. Colorscheme.active_colorscheme)
	local has_statusline_hints, StatuslineHints = pcall(require, 'statusline-action-hints')

	if has_cs then
		plugin.opts.options.theme = cs
	end

	if has_statusline_hints then
		plugin.opts.sections.lualine_x = {StatuslineHints.statusline}
	end

	require('lualine').setup(plugin.opts)
end

return M
