-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local M = {
	'Zeioth/markmap.nvim',
	build = 'yarn global add markmap-cli',
	enabled = Utils.has_tool('yarn'),
	cmd = {
		'MarkmapOpen',
		'MarkmapSave',
		'MarkmapWatch',
		'MarkmapWatchStop',
	},
	opts = {},
}

return M
