-- Do not edit this file directly! It is managed by chezmoi.

local utils = require('utils')

local M = {
	'williamboman/mason.nvim',
	enabled = false,
	build = ':MasonUpdate',
	opts = {
		ui = {
			icons = {
				package_installed = utils.get_icon('Check'),
				package_uninstalled = utils.get_icon('X'),
				packge_pending = utils.get_icon('Reload'),
			},
		},
		border = 'rounded',
	},
}

return M
