-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'andymass/vim-matchup',
}

function M.setup()
	-- Enable delete (ds%) and change (cs%) surrounding maps
	vim.g.matchup_surround_enabled = 1

	-- Don't match anything in comments
	vim.g.matchup_delim_noskips = 2
end

return M
