-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'echasnovski/mini.clue',
	opts = {
		triggers = {
			-- [] triggers
			{ mode = "n", keys = "]" },
			{ mode = "n", keys = "[" },
			-- Leader triggers
			{ mode = "n", keys = "<Leader>" },
			{ mode = "n", keys = "<LocalLeader>" },
			{ mode = "x", keys = "<Leader>" },
			{ mode = "x", keys = "<LocalLeader>" },

			-- Built-in completion
			{ mode = "i", keys = "<C-x>" },

			-- `g` key
			{ mode = "n", keys = "g" },
			{ mode = "x", keys = "g" },

			-- Marks
			{ mode = "n", keys = "'" },
			{ mode = "x", keys = "'" },

			-- Registers
			{ mode = "n", keys = '"' },
			{ mode = "x", keys = '"' },
			{ mode = "i", keys = "<C-r>" },
			{ mode = "c", keys = "<C-r>" },

			-- Window commands
			{ mode = "n", keys = "<C-w>" },

			-- `z` key
			{ mode = "n", keys = "z" },
			{ mode = "x", keys = "z" },
		},
		window = {
			delay = 0,
		},
	},
}

function M.config(_, opts)
	local MiniClue = require('mini.clue')

	opts.clues = {
		MiniClue.gen_clues.builtin_completion(),
		MiniClue.gen_clues.g(),
		MiniClue.gen_clues.marks(),
		MiniClue.gen_clues.registers(),
		MiniClue.gen_clues.windows({
			submode_move = true,
			submode_navigate = true,
			submode_resize = true,
		}),
		MiniClue.gen_clues.z(),
	}

	MiniClue.setup(opts)
end

return M
