-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'nacro90/numb.nvim',
	opts = {
		show_numbers = true,
		hide_relativenumbers = false,
		show_cursorline = true,
	},
}

return M
