-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'kosayoda/nvim-lightbulb',
	event = { 'CursorHold', 'CursorHoldI' },
	opts = {
		autocmd = {
			enabled = true,
		},
	},
}

return M
