-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')
local M = {
	'onsails/lspkind.nvim',
	dependencies = {
		'neovim/nvim-lspconfig',
	},
	opts = Utils.lspkind_opts(),
}

function M.config(_, opts)
	require('lspkind').init(opts)
end

return M
