-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'rcarriga/nvim-notify',
	dependencies = {
		'nvim-telescope/telescope.nvim',
	},
	opts = {
		stages = 'fade',
	},
}

function M.config(plugin)
	local Notify = require('notify')

	Notify.setup(plugin.opts)

	vim.notify = Notify
end

return M
