-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'utilyre/sentiment.nvim',
	version = '*',
	event = 'VeryLazy',
	opts = {},
}

function M.init()
	vim.g.loaded_matchparen = 1
end

return M
