-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local M = {
	'L3MON4D3/LuaSnip',
	dependencies = {
		'rafamadriz/friendly-snippets',
	},
	build = 'make install_jsregexp',
	enabled = Utils.has_tool('make'),
}

function M.config()
	for _, load_type in ipairs { 'vscode', 'snipmate', 'lua' } do
		local Loader = require('luasnip.loaders.from_' .. load_type)
		Loader.lazy_load()
	end
end

return M
