-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'L3MON4D3/LuaSnip',
	dependencies = {
		'rafamadriz/friendly-snippets',
	},
	build = 'make install_jsregexp',
}

function M.config()
	for _, load_type in ipairs { 'vscode', 'snipmate', 'lua' } do
		local loader = require('luasnip.loaders.from_' .. load_type)
		loader.lazy_load()
	end
end

return M
