-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

local M = {
	'simrat39/symbols-outline.nvim',
	cmd = {
		'SymbolsOutline',
		'SymbolsOutlineClose',
		'SymbolsOutlineOpen',
	},
	keys = {
		{
			'<F8>',
			function()
				require('symbols-outline').toggle_outline()
			end
		},
	},
	opts = {
		symbols = {
			File = {icon = Utils.get_icon('DefaultFile')},
			Namespace = {icon = Utils.get_icon('Array')},
			Package = {icon = Utils.get_icon('Package')},
			Class = {icon = Utils.get_icon('Class')},
			Method = {icon = Utils.get_icon('Function')},
			Property = {icon = Utils.get_icon('Setting')},
			Constructor = {icon = Utils.get_icon('Build')},
			Enum = {icon = Utils.get_icon('Enum')},
			Interface = {icon = Utils.get_icon('Interface')},
			Function = {icon = Utils.get_icon('Function')},
			String = {icon = Utils.get_icon('Font')},
			Array = {icon = Utils.get_icon('Array')},
			Key = {icon = Utils.get_icon('Key')},
		},
	},
}

return M
