-- Do not edit this file directly! It is managed by chezmoi.

local utils = require('utils')

local M = {
	'folke/trouble.nvim',
	dependencies = {
		'folke/lsp-colors.nvim',
	},
	lazy = true,
	cmd = {
		'Trouble',
		'TroubleToggle',
		'TroubleRefresh',
	},
	opts = {
		fold_closed = utils.get_icon('FoldClosed'),
		fold_open = utils.get_icon('FoldOpen'),
		open_split = { '<C-x>', 's' },
		open_vsplit = { '<C-v>', 'i', 'v' },
		open_tab = { '<C-t>', 't' },
		auto_open = true,
		auto_close = true,
		auto_preview = false,
		use_diagnostic_signs = true,
	},
}

return M
