-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'vim-latex/vim-latex',
	ft = {'latex', 'tex'},
}

function M.init()
	vim.g.tex_flavor = 'xelatex'
	vim.g.Tex_CompileRule_pdf = 'xelatex --interaction=nonstopmode $*'
end

return M
