-- Do not edit this file directly! It is managed by chezmoi.

local utils = require('utils')

local function pick_window()
	local has_picker, picker = pcall(require, 'window-picker')
	if has_picker then
		local wid = picker.pick_window() or vim.api.nvim_get_current_win()
		vim.api.nvim_set_current_win(wid)
	end
end

local M = {
	's1n7ax/nvim-window-picker',
	version = 'v1.*',
	keys = {
		{'<Leader>w', pick_window},
	},
	opts = {
		autoselect_one = true,
		include_current = true,
		filter_rules = {
			bo = {
				-- if the file type is one of following, the window will be ignored
				filetype = utils.excluded_filetypes,
				-- if the buffer type is one of following, the window will be ignored
				buftype = utils.excluded_buftypes,
			},
		},
	},
}

return M
