# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

if command -v starship >/dev/null 2>&1; then
	source <(starship init zsh)
	source <(starship completions zsh)
fi

if command -v op >/dev/null 2>&1; then
	source <(op completion zsh)
fi
