# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

if command -v starship >/dev/null 2>&1; then
	eval "$(starship init zsh)"
	eval "$(starship completions zsh)"
fi

if command -v op >/dev/null 2>&1; then
	eval "$(op completion zsh)"
fi
