# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

# Detect CPU count
CPU_COUNT=0
if (( ${+commands[nproc]} )); then
	CPU_COUNT="$(nproc)"
elif sysctl -n hw.ncpu >/dev/null 2>&1 ; then
	CPU_COUNT="$(sysctl -n hw.ncpu)"
fi
if [ "${CPU_COUNT}" -gt 1 ]; then
	export MAKEFLAGS="-j$(( CPU_COUNT - 1 ))"
fi
