" Do not edit this file directly! It is managed by chezmoi.

function! DetectJSON()
	if getline(1) =~# '^\s*{'
		setlocal filetype=jsonc
	endif
endfunction

autocmd BufNewFile,BufRead *.json,*.json.txt,.arcconfig setlocal filetype=jsonc
autocmd BufRead * call DetectJSON()
