" Do not edit this file directly! It is managed by chezmoi.

autocmd BufNewFile,BufRead *.tex setlocal filetype=latex
autocmd BufNewFile,BufRead *.cls if getline(1) =~# '^%' | setlocal filetype=latex | endif
