" Do not edit this file directly! It is managed by chezmoi.

function! DetectHackOrPHP()
	if getline(1) =~# '^<?hh'
		setlocal filetype=hack
	else
		setlocal filetype=php
	endif
endfunction

autocmd BufNewFile,BufRead *.hh,*.hhi setlocal filetype=hack
autocmd BufNewFile,BufRead *.php call DetectHackOrPHP()
