" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

augroup detectpython
	autocmd!
	autocmd BufNewFile,BufRead *.py,*.cconf,*.cinc,*.mcconf,BUCK,TARGETS set filetype=python
augroup END
