" Do not edit this file directly! It is managed by chezmoi.

autocmd BufNewFile,BufRead */cookbooks/*.rb setlocal filetype=ruby.eruby.chef
autocmd BufNewFile,BufRead */cookbooks/*.erb setlocal filetype=ruby.erb.chef
autocmd BufNewFile,BufRead *.rb setlocal filetype=ruby
