" Do not edit this file directly! It is managed by chezmoi.

function! DetectZSH()
	let s:shebang = getline(1)
	if s:shebang =~ '\bzsh\b'
		setlocal filetype=zsh
	elseif s:shebang =~ '\b(ba)?sh\b'
		setlocal filetype=sh
	endif
endfunction

autocmd BufNewFile,BufRead * call DetectZSH()
autocmd BufNewFile,BufRead PKGBUILD setlocal filetype=sh

