" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

function! DetectZSH()
	let s:shebang = getline(1)
	if s:shebang =~ '\bzsh\b'
		set filetype=zsh
	elseif s:shebang =~ '\b(ba)?sh\b'
		set filetype=sh
	endif
endfunction

augroup detectsh
	autocmd!
	autocmd BufNewFile,BufRead * call DetectZSH()
	autocmd BufNewFile,BufRead PKGBUILD set filetype=sh
augroup END

