" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

function! DetectJSON()
	if getline(1) =~# '^\s*{'
		set filetype=jsonc
	endif
endfunction

augroup detectjson
	autocmd!
	autocmd BufNewFile,BufRead *.json,*.json.txt,.arcconfig set filetype=jsonc
	autocmd BufRead * call DetectJSON()
augroup END
