" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

augroup detectthrift
	autocmd!
	autocmd BufNewFile,BufRead *.thrift set filetype=thrift
augroup END
