" Do not edit this file directly! It is managed by chezmoi.

function! import#PythonImport(fname)
	let import_line = split(a:fname, ' import ')
	let first_part = import_line[0]

	if len(import_line) > 1
		let last_part = import_line[1]
		let dot_join = join([first_part, last_part], '.')
		let candidate = substitute(dot_join, '\.', '/', 'g')
		let found = glob(candidate, 1)
		if len(found)
			return found
		endif
	endif

	return substitute(first_part, '\.', '/', 'g')
endfunction
