# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

# See https://zsh-manual.netlify.app/options for options available
setopt always_to_end auto_pushd complete_aliases correct extended_glob
setopt extended_history hist_find_no_dups hist_ignore_all_dups hist_ignore_space
setopt hist_no_store hist_reduce_blanks hist_save_no_dups hist_verify
setopt inc_append_history no_beep no_bg_nice no_flow_control no_hist_beep
setopt nomatch notify prompt_subst pushd_ignore_dups pushd_silent
setopt transient_rprompt
