# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

zmodload zsh/complete
zmodload zsh/complist
zmodload zsh/datetime
zmodload zsh/pcre
zmodload zsh/zutil

autoload -U add-zsh-hook
autoload -Uz colors

autoload -Uz compinit
compinit -d "${USER_ZSH}/zcompdump"
