# vim: set filetype=zsh:
# Do not edit this file directly! It is managed by chezmoi.

for d in "site-functions" "completion"; do
	if [ ! -d "${USER_ZSH}/${d}" ]; then
		/usr/bin/install -d -m 0700 "${USER_ZSH}/${d}"
	fi
done

typeset -U fpath
for d in /opt/homebrew/share/zsh-completions /usr/local/share/zsh-completions "${USER_ZSH}/completion" "${USER_ZSH}/site-functions"; do
	if [ -d "${d}" ]; then
		fpath=(${d} ${fpath})
	fi
done

for f in "${USER_ZSH}"/site-functions/*; do
	autoload -U "$(basename "${f%%.zwc}")"
done
