-- Do not edit this file directly! It is managed by chezmoi.

local M = {}

function M.notify(msg, title, level)
	if vim.in_fast_event() then
		return vim.schedule(function()
			M.notify(msg, opts)
		end)
	end

	vim.notify(msg, level or vim.log.levels.INFO, {
		title = title or 'Notification',
	})
end

function M.debug(msg, title)
	-- debug() may be useful for directly sending variables to for, well,
	-- debugging!
	if type(msg) ~= 'string' then
		msg = vim.inspect(msg)
	end
	M.notify(msg, title, vim.log.levels.DEBUG)
end

function M.info(msg, title)
	M.notify(msg, title, vim.log.levels.INFO)
end

function M.warn(msg, title)
	M.notify(msg, title, vim.log.levels.WARN)
end

function M.error(msg, title)
	M.notify(msg, title, vim.log.levels.ERROR)
end

return M
