-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

-- Utility functions for working around limitations in snacks.nvim
local M = {}

---@param win integer?
---@return integer
function M.pick_window(win)
	local current_wid = win or vim.api.nvim_get_current_win()

	-- If we have snacks.nvim, it's available as Snacks
	local HasSnacks, _ = pcall(require, 'snacks.picker.util')
	if not HasSnacks then
		return current_wid
	end

	local wid = Snacks.picker.util.pick_win({
		main = current_wid,
		filter = function(_, buf)
			if vim.bo[buf].filetype:find('^snacks') then
				return false
			end

			if
				vim.tbl_contains(Utils.excluded_buftypes, vim.bo[buf].buftype)
				or vim.tbl_contains(Utils.excluded_filetypes, vim.bo[buf].filetype)
			then
				return false
			end

			return true
		end,
	}) or current_wid

	return wid
end

return M
