-- Do not edit this file directly! It is managed by chezmoi.

local M = {}

---@param parsers string|string[]
function M.ensure_installed(parsers)
	local has_treesitter, TSInstall = pcall(require, 'nvim-treesitter.install')
	if not has_treesitter then
		return
	end

	TSInstall.ensure_installed(parsers)
end

return M
