" Do not edit this file directly! It is managed by chezmoi.

setlocal foldmethod=syntax

compiler go

nnoremap <LocalLeader>gb <Plug>(go-build)
nnoremap <LocalLeader>tt <Plug>(go-test)
nnoremap <LocalLeader>gr <Plug>(go-run)
