" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.
setlocal foldmethod=syntax
setlocal nospell

syntax match Comment +\/\/.\+$+

command! FormatJSON %!/usr/bin/env python3 -m json.tool
