-- vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
-- Do not edit this file directly! It is managed by chezmoi.

vim.opt_local.cindent = false
vim.opt_local.expandtab = true
vim.opt_local.iskeyword:append(':')

vim.cmd('call markdown#MathAndLiquid()')
