" vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
" vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
" Do not edit this file directly! It is managed by chezmoi.

if &diff
	" Don't fold in diffs
	set diffopt+=context:1000000
	highlight! link DiffText MatchParen
	highlight! link DiffChange Normal
	highlight! link DiffDelete Conceal
end
