-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')

vim.opt_local.iskeyword:append('@-@')

Utils.set_keymap('n', '<LocalLeader>i', function()
	local line = vim.fn.getline('.')
	if line:find('!important') then
		line = line:gsub(' !important', '')
	else
		line = line:gsub(';', ' !important;')
	end

	vim.fn.setline(vim.fn.line('.'), line)
end)
