-- Do not edit this file directly! It is managed by chezmoi.

local Utils = require('utils')
local TSUtils = require('utils.treesitter')

vim.cmd('compiler go')

Utils.set_keymap('n', '<LocalLeader>gb', '<Plug>(go-build)')
Utils.set_keymap('n', '<LocalLeader>gt', '<Plug>(go-test)')
Utils.set_keymap('n', '<LocalLeader>gr', '<Plug>(go-run)')

TSUtils.ensure_installed({ 'go', 'gomod', 'gosum' })
