-- Do not edit this file directly! It is managed by chezmoi.

local TSUtils = require('utils.treesitter')
local Utils = require('utils')

vim.cmd('compiler go')

Utils.set_keymap('n', '<LocalLeader>gb', '<Plug>(go-build)')
Utils.set_keymap('n', '<LocalLeader>gt', '<Plug>(go-test)')
Utils.set_keymap('n', '<LocalLeader>gr', '<Plug>(go-run)')

TSUtils.ensure_installed({ 'go', 'gomod', 'gosum' })

local has_post, Post = pcall(require, 'ftplugin-post.' .. vim.opt.filetype:get())
if has_post then
	Post.setup()
end
