-- Do not edit this file directly! It is managed by chezmoi.

vim.cmd('compiler go')

vim.api.nvim_create_autocmd('BufWritePre', {
	pattern = { '*.go' },
	callback = function()
		require('utils.lsp').organize_imports()
	end,
})
