-- Do not edit this file directly! It is managed by chezmoi.

local TSUtils = require('utils.treesitter')

vim.opt_local.expandtab = true

if vim.fn.executable('hh') == 1 then
	vim.g['hack#hh_client'] = 'hh'
end

vim.opt_local.iskeyword:append({ ':', '-' })
vim.opt_local.iskeyword:remove('<')

TSUtils.ensure_installed('hack')
