-- Do not edit this file directly! It is managed by chezmoi.

local homedir = os.getenv('HOME') or os.getenv('USERPROFILE')
local lib_path = homedir .. '/Documents/OpenSCAD/libraries'
if vim.fn.has('linux') == 1 or vim.fn.has('wsl') == 1 then
	lib_path = XDG_DATA_HOME .. '/OpenSCAD/libraries'
end

vim.opt_local.commentstring = '// %s'

vim.opt_local.path:append({ lib_path })
