-- Do not edit this file directly! It is managed by chezmoi.

vim.opt_local.includeexpr = 'import#PythonImport(v:fname)'
vim.opt_local.spell = false

if vim.fn.filereadable('venv/bin/python3') == 1 then
	-- TODO: This won't work on Windows.
	-- Maybe os.getenv("CD"), or io.popen("cd"):read("*l")
	vim.g.python3_host_prog = os.getenv('PWD') .. '/venv/bin/python3'
end
