" Do not edit this file directly! It is managed by chezmoi.

setlocal expandtab

let g:rubycomplete_buffer_loading = 1
let g:rubycomplete_classes_in_global = 1
compiler ruby

" <Leader># Surround a word with #{ruby interpolation}
vnoremap <buffer> <silent> <Leader># c#{<C-R>"}<ESC>
nnoremap <buffer> <silent> <Leader># bve<Leader>#
