-- Do not edit this file directly! It is managed by chezmoi.

local TSUtils = require('utils.treesitter')

vim.cmd('compiler sass')

vim.opt_local.iskeyword:append('@-@')

TSUtils.ensure_installed('scss')
