-- Do not edit this file directly! It is managed by chezmoi.

local MasonUtils = require('utils.mason')
local TSUtils = require('utils.treesitter')

TSUtils.ensure_installed('toml')
MasonUtils.ensure_installed('taplo')
