-- Do not edit this file directly! It is managed by chezmoi.

local MasonUtils = require('utils.mason')
local TSUtils = require('utils.treesitter')

vim.opt_local.spell = false

TSUtils.ensure_installed('vim')
MasonUtils.ensure_installed('vimls')
