-- Do not edit this file directly! It is managed by chezmoi.

local Ftplugin = require('utils.ftplugin')

Ftplugin.setup_markup({
	register_treesitter = {
		parser = 'html',
		filetype = 'xhtml',
	},
})
