-- Do not edit this file directly! It is managed by chezmoi.

local MasonUtils = require('utils.mason')

vim.cmd('compiler yamllint')

vim.opt_local.expandtab = true
vim.opt_local.spell = false
vim.opt_local.textwidth = 120

MasonUtils.ensure_installed('yamlls')

local HasLocalConfig, LocalConfig = pcall(require, 'local.ftplugin.yaml')
if HasLocalConfig then
	LocalConfig.setup()
end
