[packages]
[packages.darwin]
brew = [
	"bat",
	"bottom",
	"chezmoi",
	"coreutils",
	"fd",
	"fortune",
	"fzf",
	"git",
	"git-absorb",
	"git-extras",
	"gnupg",
	"go",
	"imagemagick",
	"jq",
	"lazygit",
	"lsd",
	"lunchy",
	"mas",
	"neovim",
	"npm",
	"pinentry-mac",
	"pre-commit",
	"procs",
	"pstree",
	"python3",
	"rename",
	"ripgrep",
	"starship",
	"yq",
	"zsh",
	"zsh-autosuggestions",
	"zsh-syntax-highlighting",
]

cask = [
	"1password",
	"1password-cli",
	"alfred",
	"discord",
	"firefox",
	"google-chrome",
	"joplin",
	"kitty",
]

# App Store installs, find the ID and string to use with `mas list`
[[packages.darwin.mas]]
name = "1Password for Safari"
id = 1569813296

[[packages.darwin.mas]]
name = "Baking Soda"
id = 1601151613

[[packages.darwin.mas]]
name = "Hand Mirror"
id = 1502839586

[[packages.darwin.mas]]
name = "Vinegar"
id = 1591303229

[packages.darwin.personal]
brew = ["rust"]
cask = ["calibre"]

[[packages.darwin.personal.mas]]
name = "OneDrive"
id = 823766827

[packages.darwin.work]
brew = []
cask = []
mas = []

[packages.darwin.headless]
brew = []
cask = []
mas = []

[packages.arch]
pacman = [
	"base",
	"base-devel",
	"ark",
	"avahi",
	"bat",
	"bluez",
	"bluez-utils",
	"bottom",
	"chezmoi",
	"chrony",
	"colord",
	"colord-kde",
	"cpio",
	"cups",
	"cups-browsed",
	"cups-filters",
	"cups-pdf",
	"cups-pk-helper",
	"curl",
	"dhclient",
	"direnv",
	"discord",
	"dolphin",
	"dolphin-plugins",
	"efivar",
	"fd",
	"ffmpeg",
	"ffmpegthumbnailer",
	"ffmpegthumbs",
	"firefox",
	"firewalld",
	"flatpak",
	"flatpak-xdg-utils",
	"foomatic-db",
	"foomatic-db-gutenprint-ppds",
	"foomatic-db-ppds",
	"foomatic-db-nonfree",
	"foomatic-db-nonfree-ppds",
	"fortune-mod",
	"fprintd",
	"fwupd",
	"fwupd-efi",
	"fzf",
	"git",
	"git-crypt",
	"gnupg",
	"go",
	"gutenprint",
	"imagemagick",
	"inetutils",
	"iptables-nft",
	"jq",
	"kde-gtk-config",
	"kde-inotify-survey",
	"kdegraphics-thumbnailers",
	"kimageformats",
	"kio-admin",
	"kio-extras",
	"kio-fuse",
	"kio-zeroconf",
	"kitty",
	"kwallet",
	"kwallet-pam",
	"kwalletmanager",
	"lazygit",
	"less",
	"libappindicator-gtk3",
	"libxml2",
	"lsd",
	"lua51",
	"luajit",
	"man-db",
	"man-pages",
	"neovim",
	"networkmanager",
	"nextcloud-client",
	"nftables",
	"noto-fonts",
	"npm",
	"nss-mdns",
	"phonon-qt6",
	"phonon-qt6-vlc",
	"plasma-meta",
	"plasma-nm",
	"platformio-core-udev",
	"plocate",
	"polkit",
	"polkit-kde-agent",
	"powerdevil",
	"power-profiles-daemon",
	"pre-commit",
	"print-manager",
	"procs",
	"python-pip",
	"python-pynvim",
	"qt6-imageformats",
	"ripgrep",
	"rsync",
	"sd",
	"sddm",
	"sddm-kcm",
	"seahorse",
	"signal-desktop",
	"starship",
	"thermald",
	"thunderbird",
	"ttf-dejavu",
	"ttf-hannom",
	"ttf-khmer",
	"ttf-liberation",
	"ttf-scheherazade-new",
	"unace",
	"unarj",
	"unrar",
	"unzip",
	"usbutils",
	"webp-pixbuf-loader",
	"wget",
	"wpa_supplicant",
	"xdg-desktop-portal",
	"xdg-desktop-portal-gtk",
	"xdg-desktop-portal-kde",
	"xdg-user-dirs",
	"xdg-utils",
	"xsettingsd",
	"yq",
	"zip",
	"zsh",
	"zsh-autosuggestions",
	"zsh-completions",
	"zsh-syntax-highlighting",
]

aur = [
	"1password",
	"1password-cli",
	"fortune-mod-calvin",
	"fortune-mod-canada-nctr",
	"fortune-mod-cybersuntzu",
	"fortune-mod-doctorwho-classic-series",
	"fortune-mod-doctorwho-new-series",
	"fortune-mod-ferengi_rules_of_acquisition",
	"fortune-mod-firefly",
	"fortune-mod-leftism-git",
	"fortune-mod-montypython",
	"fortune-mod-portal-game",
	"fortune-mod-question-answer-jokes",
	"fortune-mod-starwars",
	"fortune-mod-vimtips",
	"kio-onedrive-git",
	"networkmanager-dispatcher-chrony",
	"orca-slicer-bin",
	"ttf-ancient-fonts",
	"ttf-qurancomplex-fonts",
]

[packages.fedora]
copr = ["atim/bottom", "atim/lazygit", "atim/starship"]

dnf = [
	"bat",
	"bottom",
	"clang",
	"compat-lua-devel",
	"fd-find",
	"ffmpeg",
	"firefox",
	"fortune-mod",
	"fzf",
	"git",
	"git-absorb",
	"git-extras",
	"gnupg2",
	"golang-bin",
	"ImageMagick",
	"jq",
	"kitty",
	"lazygit",
	"lsd",
	"neovim",
	"nodejs-npm",
	"onedrive",
	"pre-commit",
	"python3-neovim",
	"python3-pip",
	"ripgrep",
	"rust",
	"rust-src",
	"starship",
	"thunderbird",
	"yq",
	"zsh",
	"zsh-autosuggestions",
	"zsh-syntax-highlighting",
]
removal = ["libswscale-free"]

[[packages.fedora.flatpak]]
name = "com.discordapp.Discord"
remote = "flathub"

[[packages.fedora.flatpak]]
name = "net.cozic.joplin_desktop"
remote = "flathub"

[packages.windows]
powershell = [
	"AdvancedHistory",
	"Microsoft.PowerShell.SecretManagement",
	"Microsoft.PowerShell.SecretStore",
]

winget = [
	"AgileBits.1Password",
	"Discord.Discord",
	"EpicGames.EpicGamesLauncher",
	"GIMP.GIMP",
	"Microsoft.PowerShell",
	"Microsoft.PowerToys",
	"Microsoft.VisualStudioCode",
	"Mozilla.Firefox",
	"Mozilla.Thunderbird",
	"Roblox.Roblox",
	"Valve.Steam",
]

msstore = [
	"9PMMSR1CGPWG", # HEIF extensions
]

[packages.windows.scoop]
buckets = ["extras"]
packages = [
	"1password-cli",
	"age",
	"chezmoi",
	"fzf",
	"gcc",
	"git",
	"go",
	"gsudo",
	"lazygit",
	"neovim",
	"nodejs",
	"python",
	"ripgrep",
	"rust",
	"starship",
	"vcredist2022",
	"wezterm",
]
