-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.servers = opts.servers or {}
			local base_cmd = vim.deepcopy((opts.servers.clangd and opts.servers.clangd.cmd) or { 'clangd' })

			local new_settings = {
				cmd = function(dispatchers, config)
					local function has_file(path)
						return vim.fn.filereadable(path) == 1
					end

					local function append_cmd_flag(cmd, flag)
						if not vim.tbl_contains(cmd, flag) then
							table.insert(cmd, flag)
						end
					end

					local cmd = vim.deepcopy(base_cmd)
					local root_dir = config.root_dir
					if not root_dir or root_dir == '' then
						return vim.lsp.rpc.start(cmd, dispatchers, {
							cwd = config.cmd_cwd,
							env = config.cmd_env,
							detached = config.detached,
						})
					end

					local root_compile_commands = root_dir .. '/compile_commands.json'
					local build_dir = root_dir .. '/build'
					local build_compile_commands = build_dir .. '/compile_commands.json'

					if not has_file(root_compile_commands) and not has_file(build_compile_commands) then
						local result = nil

						if has_file(root_dir .. '/platformio.ini') then
							result = vim.system({ 'pio', 'run', '-t', 'compiledb' }, { cwd = root_dir, text = true }):wait()
						elseif has_file(root_dir .. '/CMakeLists.txt') then
							vim.fn.mkdir(build_dir, 'p')
							result = vim
								.system({ 'cmake', '-S', root_dir, '-B', build_dir, '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON' }, { text = true })
								:wait()
						end

						if result and result.code ~= 0 then
							vim.schedule(function()
								vim.notify(
									('Failed to generate compile_commands.json for %s\n%s'):format(root_dir, result.stderr or ''),
									vim.log.levels.WARN,
									{ title = 'clangd' }
								)
							end)
						end
					end

					if has_file(build_compile_commands) then
						append_cmd_flag(cmd, '--compile-commands-dir=' .. build_dir)
					end

					if has_file(root_dir .. '/platformio.ini') then
						append_cmd_flag(cmd, '--compile-commands-dir=' .. root_dir)
						append_cmd_flag(
							cmd,
							'--query-driver=' .. os.getenv('HOME') .. '/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++'
						)
					end

					config._resolved_cmd = vim.deepcopy(cmd)

					return vim.lsp.rpc.start(cmd, dispatchers, {
						cwd = config.cmd_cwd,
						env = config.cmd_env,
						detached = config.detached,
					})
				end,
			}

			opts.servers.clangd = vim.tbl_deep_extend('force', opts.servers.clangd or {}, new_settings)
		end,
	},
}

return M
