-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			local filters = opts['servers']['gopls']['settings']['gopls']['directoryFilters'] or {}
			for _, d in ipairs({ '-.hg', '-bazel-bin', '-bazel-out', '-bazel-testlogs', '-bazel-gosre', '-bazel-genfiles' }) do
				table.insert(filters, d)
			end
			opts['servers']['gopls']['settings']['gopls']['directoryFilters'] = filters

			opts['servers']['gopls']['settings']['gopls']['staticcheck'] = true

			opts['servers']['gopls']['settings']['gopls']['vulncheck'] = 'Imports'
		end,
	},
	{
		'maxandron/goplements.nvim',
		ft = 'go',
		opts = {},
	},
}

return M
