-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			local filters = opts['servers']['gopls']['settings']['gopls']['directoryFilters'] or {}
			table.insert(filters, '-.hg')
			table.insert(filters, '-bazel-bin')
			table.insert(filters, '-bazel-out')
			table.insert(filters, '-bazel-testlogs')
			opts['servers']['gopls']['settings']['gopls']['directoryFilters'] = filters
		end,
	},
	{
		'williamboman/mason.nvim',
		opts = function(_, opts)
			table.insert(opts.ensure_installed, 'golines')
		end,
	},
	{
		'stevearc/conform.nvim',
		opts = function(_, opts)
			opts.formatters_by_ft['go'] = opts.formatters_by_ft['go'] or {}
			table.insert(opts.formatters_by_ft.go, 'golines')
		end,
	},
}

return M
