-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			local goplsSettings = {
				-- See https://go.googlesource.com/tools/+/master/gopls/doc/analyzers.md#replace-interface_with-any for valid
				-- analyzer names.
				analyses = {
					unusedresult = false,
				},
				directoryFilters = { '-.hg', '-.git' },
				semanticTokens = true,
				staticcheck = true,
				vulncheck = 'Imports',
			}

			opts['servers']['gopls']['settings']['gopls'] =
				vim.tbl_deep_extend('force', opts['servers']['gopls']['settings']['gopls'] or {}, goplsSettings)
		end,
	},
	{
		'maxandron/goplements.nvim',
		ft = 'go',
		opts = {},
	},
}

return M
