-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		local filters = opts['servers']['gopls']['settings']['gopls']['directoryFilters'] or {}
		table.insert(filters, '-.hg')
		opts['servers']['gopls']['settings']['gopls']['directoryFilters'] = filters
	end,
}

return M
