-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.servers = opts.servers or {}
			opts.servers.html = opts.servers.html or {}

			local html_settings = {
				html = {
					format = {
						indentInnerHtml = true,
					},
				},
			}

			opts.servers.html.settings = vim.tbl_deep_extend('force', opts.servers.html.settings or {}, html_settings)
		end,
	},
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'html-lsp', 'htmlbeautifier', 'htmlhint' } },
	},
}

return M
