-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-treesitter/nvim-treesitter',
		opts = { ensure_installed = { 'jsonnet' } },
	},
	{
		'neovim/nvim-lspconfig',
		opts = {
			servers = {
				jsonnet_ls = {
					settings = {
						formatting = {
							Indent = 2,
						},
					},
				},
			},
		},
	},
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'jsonnet-language-server' } },
	},
}

return M
