-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-treesitter/nvim-treesitter',
		opts = function(_, opts)
			vim.list_extend(opts.ensure_installed, { 'jsonnet' })
		end,
	},
	{
		'neovim/nvim-lspconfig',
		opts = {
			servers = {
				jsonnet_ls = {
					settings = {
						formatting = {
							Indent = 2,
						},
					},
				},
			},
		},
	},
	{
		'williamboman/mason.nvim',
		opts = function(_, opts)
			opts.ensure_installed = opts.ensure_installed or {}
			vim.list_extend(opts.ensure_installed, { 'jsonnet-language-server' })
		end,
	},
}

return M
