-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	dependencies = {
		'b0o/SchemaStore.nvim',
	},
	opts = function(_, opts)
		opts['servers']['jsonls']['settings']['schemas'] = require('schemastore').json.schemas()
	end,
}

return M
