-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'https://codeberg.org/jgoguen/jsonl.nvim',
		dependencies = { 'romus204/tree-sitter-manager.nvim' },
		ft = { 'jsonl' },
		opts = {},
	},
}

return M
