-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.servers = opts.servers or {}
			opts.servers.lua_ls = opts.servers.lua_ls or {}
			opts.servers.lua_ls.settings = opts.servers.lua_ls.settings or {}

			local lua_settings = {
				Lua = {
					completion = {
						callSnippet = 'Both',
						keywordSnippet = 'Both',
					},
					diagnostics = {
						globals = {
							'Lazy',
							'Snacks',
							'_G',
							'ipairs',
							'nvim',
							'os',
							'pcall',
							'require',
							'vim',
						},
					},
					format = {
						defaultConfig = {
							break_all_list_when_line_exceed = true,
							end_of_line = 'LF',
							quote_style = 'single',
							trailing_table_separator = 'smart',
						},
					},
					hint = {
						setType = true,
					},
					IntelliSense = {
						traceLocalSet = true,
						traceReturn = true,
					},
					runtime = {
						version = 'Lua 5.1',
					},
					telemetry = {
						enable = false,
					},
					workspace = {
						library = vim.api.nvim_get_runtime_file('', true),
					},
				},
			}

			opts.servers.lua_ls.settings = vim.tbl_deep_extend('force', opts.servers.lua_ls.settings, lua_settings)
		end,
	},
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'lua-language-server' } },
	},
	{
		'nvim-treesitter/nvim-treesitter',
		opts = { ensure_installed = { 'lua', 'luadoc', 'luap' } },
	},
	{
		'mfussenegger/nluarepl',
	},
}

return M
