-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		opts['servers']['lua_ls']['settings']['Lua']['completion']['callSnippet'] = 'Both'
		opts['servers']['lua_ls']['settings']['Lua']['completion']['keywordSnippet'] = 'Both'

		opts['servers']['lua_ls']['settings']['Lua']['diagnostics'] = {
			globals = {
				'nvim',
				'vim',
				'require',
				'pcall',
				'_G',
				'os',
				'ipairs',
			},
		}

		opts['servers']['lua_ls']['settings']['Lua']['format'] = opts['servers']['lua_ls']['settings']['Lua']['format']
			or {}
		opts['servers']['lua_ls']['settings']['Lua']['format']['defaultConfig'] = {
			break_all_list_when_line_exceed = true,
			end_of_line = 'LF',
			quote_style = 'single',
			trailing_table_separator = 'smart',
		}

		opts['servers']['lua_ls']['settings']['Lua']['hint']['setType'] = true

		opts['servers']['lua_ls']['settings']['Lua']['IntelliSense'] = {
			traceLocalSet = true,
			traceReturn = true,
		}

		opts['servers']['lua_ls']['settings']['Lua']['runtime'] = {
			version = 'Lua 5.1',
		}

		opts['servers']['lua_ls']['settings']['Lua']['telemetry'] = {
			enable = false,
		}

		opts['servers']['lua_ls']['settings']['Lua']['workspace']['library'] = vim.api.nvim_get_runtime_file('', true)
	end,
}

return M
