-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		opts['servers']['lua_ls']['settings']['Lua']['IntelliSense'] = {
			traceLocalSet = true,
			traceReturn = true,
		}
		opts['servers']['lua_ls']['settings']['Lua']['telemetry'] = {
			enable = false,
		}
		opts['servers']['lua_ls']['settings']['Lua']['runtime'] = {
			version = 'LuaJIT',
		}
		opts['servers']['lua_ls']['settings']['Lua']['diagnostics'] = {
			globals = {
				'nvim',
				'vim',
				'require',
				'pcall',
				'_G',
				'os',
				'ipairs',
			},
		}
		opts['servers']['lua_ls']['settings']['Lua']['workspace']['library'] = vim.api.nvim_get_runtime_file('', true)
	end,
}

return M
