-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'vim-pandoc/vim-pandoc',
		lazy = false,
		init = function()
			vim.g['pandoc#filetypes#pandoc_markdown'] = 0

			vim.treesitter.language.register('markdown', { 'markdown.pandoc' })
		end,
	},
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts['servers']['prosemd_lsp'] = {
				filetypes = {
					'markdown',
					'markdown.pandoc',
				},
			}
		end,
	},
}

return M
