-- Do not edit this file directly! It is managed by chezmoi.

local marksman_root_files = {
	'.git',
	'.marksman.toml',
	'Cargo.toml',
	'MODULE.bazel',
	'.hg',
	'go.mod',
	'go.sum',
	'go.work',
}

local marksman_filetypes = {
	'markdown',
	'markdown.mdx',
	'markdown.gfm',
	'markdown.pandoc',
}

local M = {
	{
		'vim-pandoc/vim-pandoc',
		ft = { 'markdown' },
		init = function()
			vim.g['pandoc#filetypes#pandoc_markdown'] = 0

			vim.treesitter.language.register('markdown', { 'markdown.pandoc' })
		end,
	},
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts.servers.marksman.filetypes = opts.servers.marksman.filetypes or {}
			for _, ftype in ipairs(marksman_filetypes) do
				if not vim.tbl_contains(opts.servers.marksman.filetypes, ftype) then
					table.insert(opts.servers.marksman.filetypes, ftype)
				end
			end

			opts.servers.marksman.root_markers = opts.servers.marksman.root_markers or {}
			for _, name in ipairs(marksman_root_files) do
				if not vim.tbl_contains(opts.servers.marksman.root_markers, name) then
					table.insert(opts.servers.marksman.root_markers, name)
				end
			end
		end,
	},
	{
		'stevearc/conform.nvim',
		opts = {
			formatters_by_ft = {
				['markdown.pandoc'] = { 'prettier', 'markdownlint-cli2', 'markdown-toc' },
			},
		},
	},
	{
		'mfussenegger/nvim-lint',
		opts = {
			linters_by_ft = {
				['markdown.pandoc'] = { 'markdownlint-cli2' },
			},
		},
	},
}

return M
