-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		opts = function(_, opts)
			opts['servers']['openscad_lsp'] = opts['servers']['openscad_lsp'] or {}
		end,
	},
}

return M
