-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		opts['servers']['prosemd_lsp'] = {
			filetypes = {
				'markdown',
				'markdown.pandoc',
			},
		}
	end,
}

return M
