-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'nvim-treesitter/nvim-treesitter',
		opts = { ensure_installed = { 'python' } },
	},
	{
		'neovim/nvim-lspconfig',
		opts = {
			servers = {
				basedpyright = {
					settings = {
						basedpyright = {
							analysis = {
								autoImportCompletions = true,
								autoSearchPaths = true,
								-- Ignore in favour of ruff
								ignore = { '*' },
							},
							disableOrganizeImports = true,
						},
						python = {
							pythonPath = vim.g.python3_host_prog,
						},
					},
				},
			},
		},
	},
}

return M
