-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		opts['servers']['basedpyright'] = {
			enabled = true,
			settings = {
				exclude = {
					'venv',
					'.venv',
					'env',
				},
				basedpyright = {
					analysis = {
						autoImportCompletions = true,
						autoSearchPaths = true,
						diagnosticMode = 'workspace',
						useLibraryCodeForTypes = true,
					},
				},
			},
		}

		opts['servers']['ruff'] = opts['servers']['ruff'] or {}
		opts['servers']['ruff']['init_options'] = opts['servers']['ruff']['init_options'] or {}
		opts['servers']['ruff']['init_options']['lint'] = {
			exclude = { '*' },
		}

		opts['servers']['basedpyright']['settings']['python'] = opts['servers']['basedpyright']['settings']['python'] or {}
		opts['servers']['basedpyright']['settings']['python']['pythonPath'] = vim.g.python3_host_prog
	end,
}

return M
