-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'stevearc/conform.nvim',
		opts = {
			formatters_by_ft = {
				sh = { 'shfmt' },
				bash = { 'shfmt' },
				zsh = { 'shfmt' },
			},
			formatters = {
				shfmt = {
					prepend_args = function(_, ctx)
						local expand = vim.bo[ctx.buf].expandtab
						local ts = vim.bo[ctx.buf].tabstop or 4
						local indent = expand and ts or 0

						return { '-i', tostring(indent), '-ci', '-bn', '-kp' }
					end,
				},
			},
		},
	},
	{
		'mason.org/mason.nvim',
		opts = {
			ensure_installed = { 'bash-language-server', 'shfmt' },
		},
	},
}

return M
