-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'mason-org/mason.nvim',
		opts = { ensure_installed = { 'taplo' } },
	},
	{
		'nvim-treesitter/nvim-treesitter',
		opts = { ensure_installed = { 'toml' } },
	},
}

return M
