-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	opts = function(_, opts)
		opts['servers']['yamlls']['settings']['yaml']['customTags'] = {
			'!include_dir_named',
			'!input scalar',
			'!lambda scalar',
			'!secret scalar',
		}
		opts['servers']['yamlls']['settings']['yaml']['format']['printWidth'] = 120
		opts['servers']['yamlls']['settings']['yaml']['format']['singleQuote'] = true
		opts['servers']['yamlls']['settings']['yaml']['schemas'] = {
			['http://json.schemastore.org/github-workflow'] = '.github/workflows/*.{yml,yaml}',
			['http://json.schemastore.org/github-action'] = '.github/action.{yml,yaml}',
			['http://json.schemastore.org/ansible-stable-2.9'] = 'roles/tasks/*.{yml,yaml},',
		}
	end,
}

return M
