-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	'neovim/nvim-lspconfig',
	dependencies = {
		'b0o/SchemaStore.nvim',
	},
	opts = function(_, opts)
		opts['servers']['yamlls']['settings']['yaml']['customTags'] = {
			'!include_dir_named',
			'!input scalar',
			'!lambda scalar',
			'!secret scalar',
		}
		opts['servers']['yamlls']['settings']['yaml']['format']['printWidth'] = 120
		opts['servers']['yamlls']['settings']['yaml']['format']['singleQuote'] = true
	end,
}

return M
