-- Do not edit this file directly! It is managed by chezmoi.

local M = {
	{
		'neovim/nvim-lspconfig',
		dependencies = {
			'b0o/SchemaStore.nvim',
		},
		opts = {
			servers = {
				yamlls = {
					settings = {
						yaml = {
							customTags = {
								'!include_dir_named',
								'!input scalar',
								'!lambda scalar',
								'!secret scalar',
							},
							format = {
								printWidth = 120,
								singleQuote = true,
							},
							schemaStore = {
								enable = false,
								url = '',
							},
							schemas = require('schemastore').yaml.schemas(),
						},
					},
				},
			},
		},
	},
}

return M
