"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

format = """\
$command_duration\
$username\
$hostname\
$directory\
$git_branch\
${custom.stgit} \
$git_state\
$git_status\
$c\
$dotnet\
$golang\
$lua\
$python\
$ruby\
$perl\
$php\
$rust\
$battery\
$time \
$line_break\
$status\
$character\
"""

[username]
show_always = true
style_user = "bold blue"
format = "[$user]($style)"

[[battery.display]]
threshold = 50

[hostname]
ssh_only = true
style = "bold green"
format = " on [$hostname]($style)"

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = '…/'
style = "bold yellow"
read_only = " "
format = " in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold purple"

[hg_branch]
symbol = " "
style = "bold purple"

[git_commit]
style = "bold cyan"

[status]
disabled = false
format = "[$symbol$status]($style) "
map_symbol = true
pipestatus = true

[sudo]
disabled = false

[time]
disabled = false

[character]
success_symbol = "[%](bold white)"
error_symbol = "[%](bold red)"

[custom.hgcommit]
command = "hg_commit.sh"
when = "hg st"
format = "[on](bold white) [$output]($style)"
style = "bold purple"

[custom.hgremote]
command = "hg_remote_name.sh"
when = "hg st"
style = "bold cyan"

[custom.hgstate]
command = "hg_state.sh"
when = "hg st"
format = "[($output)]($style)"
style = "bold yellow"

[custom.hgstatus]
command = "hg_status.sh"
when = "hg st"
style = "bold red"

# Adds 200-500ms to the prompt
[custom.stgit]
command = "stg series --short=0 -P"
require_repo = true
when = "stg series"
description = "show stacked-git patch"
symbol = " "
format = "[$symbol$output]($style)"

[c]
symbol = " "

[memory_usage]
disabled = false

[golang]
symbol = " "

[docker_context]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
