-- vim: set noexpandtab tabstop=2 shiftwidth=2 autoindent:
-- vim: set foldmarker=[[[,]]] foldmethod=marker foldlevel=0:
-- Do not edit this file directly! It is managed by chezmoi.

local has_lspconfig, lspconfig = pcall(require, 'lspconfig')
if not has_lspconfig then
	return
end

local lsputils = require("lsputils")
local capabilities = lsputils.capabilities

local servers = { "gopls", "pyright" }

local lsp_settings = {
	pyright = {
		python = {
			pythonPath = "python3",
		},
	},
}

for _, lsp in ipairs(servers) do
	local settings = lsp_settings[lsp] or lspconfig[lsp].settings
	lspconfig[lsp].setup({
		capabilities = capabilities,
		settings = settings,
		on_attach = lsputils.on_attach,
	})
end
